### ISSUE TITLE
bpf_core_read returns incorrect value

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#1124]
`bpf_core_read` and `bpf_probe_read` returns different values for the same thing.
I am trying to get the `sa_family` of a `sock_addr` struct, using `READ_KERN` returned 0 instead of 2.
When examining the differences between values of `bpf_core_read` and `bpf_probe_read`, it seems that the `bpf_core_read` returns 0 instead of the correct value.

Running on Ubuntu 20.10 (Groovy Gorilla) kernel version:
```Linux ubuntu 5.8.0-63-generic #71-Ubuntu SMP Tue Jul 13 15:59:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux```

Example code showing this bug:
https://github.com/AsafEitani/tracee/tree/core_bug

The results when running tracee-ebpf and connecting two netcat instances to each other:
![image](https://user-images.githubusercontent.com/54033369/140297800-78aa2562-bc18-43b3-aa3d-c33eee1070bc.png)

The command used:
```sudo dist/tracee-ebpf -t e=accept4,full_socket_accept```

**Comment by yanivagman** [comment]
Tracee doesn't have `full_socket_accept` event.
Does this issue happens on any of the events of tracee, or only in this event you added?

**Comment by AsafEitani** [comment]
In the branch I attached I added the event to explain the issue.
This branch is also based on the updated main.
@rafaeldtinoco

**Comment by rafaeldtinoco** [comment]
@AsafEitani 

Okay, I've done some debugging in your code. It turns out you're trying to read CORE from kernel memory while the argument being passed to the function being probed (sys_accept4) is in USER memory address (this is usually true for syscalls only, because arguments are coming from userland and kernel needs to copy userland buffer into kernel memory). 

Do use `bpf_core_read_user()` instead of `bpf_core_read()` and you will get the value 2 in your example.

Now...

If you allow me, instead of calling 2 times bpf_core_read_user(), like you've done, its always faster to call it once for the entire struct, and then use values from the function stack to submit to buffer.

Using your example, just to illustrate:
```
      int sockfd = (int)sys->args.args[0];                                                                         
      struct sockaddr new = {}, *addr = (struct sockaddr *) sys->args.args[1];    
                                                                                                                   
      bpf_core_read_user(&new, sizeof(struct sockaddr), addr);                                                     
      
      u16 sa_fam = new.sa_family;                                                                                  
      u16 sa_fam_core = new.sa_family;                                                                             
                                                                                                                   
      save_to_submit_buf(&data, (void *)&sockfd, sizeof(int), 0);                                                  
      save_to_submit_buf(&data, (void *)&sa_fam, sizeof(u16), 1);                                                  
      save_to_submit_buf(&data, (void *)&sa_fam_core, sizeof(u16), 2);                                             

      return events_perf_submit(&data, FULL_SOCKET_ACCEPT, 0);
```
the result:
```
TIME             UID    COMM             PID     TID     RET              EVENT                ARGS
00:50:14:319578  1000   nc               238389  238389  0                full_socket_accept   sockfd: 3, family_probe: 2, family_core: 2
```

Hope it helps you!

Cheers

**Comment by yanivagman** [comment]
@rafaeldtinoco that's interesting, do you know why exactly bpf_core_read() fails while bpf_core_read_user() not?
Eventually, bpf_core_read() is just a regular bpf_probe_read() with builtin_preserve_access directive, so why would struct sockaddr fields will look differently with this directive? I mean, sa_fam field of sockaddr is at offset 0, what exactly the problem here?

Anyways, that's a good opportunity to emphasis the importance of #559 we should do. As a first step, we can add a new READ_USER macro that will use bpf_probe_read_user() for non-CORE environments and bpf_core_read_user() when CORE is enabled.

**Comment by rafaeldtinoco** [comment]
> @rafaeldtinoco that's interesting, do you know why exactly bpf_core_read() fails while bpf_core_read_user() not? Eventually, bpf_core_read() is just a regular bpf_probe_read() with builtin_preserve_access directive, so why would struct sockaddr fields will look differently with this directive? I mean, sa_fam field of sockaddr is at offset 0, what exactly the problem here?

bpf_core_read() => bpf_probe_read_kernel(dst, sz, preserve_access_index(src))
bpf_core_read_user() => bpf_probe_read_user(dst, sz, preserve_access_index(src))

Difference among them is that without using bpf_core_read_user(), kernel won't copy from user and give back a valid kernel address pointer:

```C
static __always_inline int
bpf_probe_read_user_common(void *dst, u32 size, const void __user *unsafe_ptr)
{
	int ret;

	ret = copy_from_user_nofault(dst, unsafe_ptr, size);
	if (unlikely(ret < 0))
		memset(dst, 0, size);
	return ret;
}

BPF_CALL_3(bpf_probe_read_user, void *, dst, u32, size,
	   const void __user *, unsafe_ptr)
{
	return bpf_probe_read_user_common(dst, size, unsafe_ptr);
}
```

That differentiates both bpf_core_read_{kernel,user} helpers. I think bpf_probe_read() worked, from his first case, because it has a compatibility layer that tries reading from user memory address space before reading the kernel address space:

```C
#ifdef CONFIG_ARCH_HAS_NON_OVERLAPPING_ADDRESS_SPACE
	case BPF_FUNC_probe_read:
		return security_locked_down(LOCKDOWN_BPF_READ_KERNEL) < 0 ?
		       NULL : &bpf_probe_read_compat_proto;
	case BPF_FUNC_probe_read_str:
		return security_locked_down(LOCKDOWN_BPF_READ_KERNEL) < 0 ?
		       NULL : &bpf_probe_read_compat_str_proto;
#endif
```

```C
BPF_CALL_3(bpf_probe_read_compat_str, void *, dst, u32, size,
	   const void *, unsafe_ptr)
{
	if ((unsigned long)unsafe_ptr < TASK_SIZE) {
		return bpf_probe_read_user_str_common(dst, size,
				(__force void __user *)unsafe_ptr);
	}
	return bpf_probe_read_kernel_str_common(dst, size, unsafe_ptr);
}
```

But, for CO-RE, you need to specifically tell which version you want, kernel or user, as the offset relocation might change "the game" during runtime (thats my guess).

> 
> Anyways, that's a good opportunity to emphasis the importance of #559 we should do. As a first step, we can add a new READ_USER macro that will use bpf_probe_read_user() for non-CORE environments and bpf_core_read_user() when CORE is enabled.

Agreed.

**Comment by rafaeldtinoco** [comment]
@AsafEitani I'm closing this as I think we've covered it all. Let me know if not, please. And thanks for opening it so discussions were made, it makes things easy on our side. Cheers!
