### ISSUE TITLE
tracee-ebpf: Unmatched types of context and external.event members

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#1138]
### The Issue
I noticed that almost all the members of the `context` struct, which is the event's struct before processing by the user-space, are not matching the `external.event`'s members types.
In particular, the main difference is that most of the members in the `context` struct are `uint` in different sizes, and in the `external.Event` they are a simple `int` type - not matching with negative values and even by size. It is an opening to bugs and even security issues, because some of the values might in some cases be changed in unpredicted ways.
### Examples For Issues
For example, if tracee runs on machine with many processes which are created and closed the PID given might turn into a negative value which is not a possible value of PID. Timestamps are a great place for issues (because the clock could be altered) and so on.
### My Opinion
I think we should change the `external.Event` members types to match the `context` sturct.

**Comment by itaysk** [comment]
The difference in types is intentional. context is internal concept and should serve to process events from kernel, therefore it's types should closely match the kernel types. Event is external concept and should serve to consume events by user, therefor it's types should match the use case. User should not be bothered with internal concepts (as much as possible), Tracee-eBPF should emit Events in a stable and user-friendly interface.

About the pid example - I think it's an issue to be fixed in context, not in Event, since `pid_t` is `int`, not `uint`.
About timestamps - need to better understand the potential issue. But just to make the point, IMO it would be more sense to widen the gap here and use Go native types like `Time` in Event rather than to closing the gap by trying to match the kernel behavior.

**Comment by AlonZivony** [comment]
After looking at it deeply it seems that you are right.
I don't see a specific field which the cast is problematic in, even more so if the time is converted to `Time` type. It is also true that `time_t` and `pid_t` in the kernel are typedefs of `int`, though it seems from forums I looked at that PID numbers range could be modified to extend it, and part of the time functions use `uint` and I am not sure what is the type relevant to us. Anyways, it seems that there is no obvious harm in the current `external.Event` members types.
My only concern that there are some edge cases that we can't predict today that might cause problems in the future.
Tracee `context` type matches the return types from BPF helpers functions, so unless we want to do casting in the BPF code I think the current way is safe.

**Comment by itaysk** [comment]
so we agree Event shouldn't match context, but feel free to fix context to more accurately match the kernel types though
