### ISSUE TITLE
Don't compile non-CO-RE artifact on BTF enabled environments

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#1178]
Currently, our default makefile target compiles both CO-RE and non-CO-RE bpf artifacts.
For environments which have BTF enabled, there is no need to compile the non-CO-RE artifact as it will not be used by tracee.
On such environments, we should only compile the non-CO-RE artifact if specifically requested by the user (e.g. using the bpf target)

**Comment by rafaeldtinoco** [comment]
Agreed. I've been commenting non CO-RE compilation multiple times to reduce burden in development, so +1 here.

**Comment by rafaeldtinoco** [comment]
We decided that we won't build non-CO-RE by default and it is being implemented at: https://github.com/aquasecurity/tracee/pull/1273. I have already implemented the "not compiling non CO-RE by default at https://github.com/aquasecurity/tracee/pull/1227.

Because of that, I think we can close this. I'm doing so. Please re-open if you think its needed.
