### ISSUE TITLE
some question about execve problem bcc #2627

### ISSUE THREAD

**Issue by jhyang0223** [aquasecurity/tracee#138]
I tested about execve problem(bcc #2627 test program) in my ubuntu.
I tested it in kernel version 4.18 and 5.3.
But tracee recorded execve's parameter ('/bin/ls') well.
I can't understand why tracee records parameters well in my ubuntu...

Does any patch applied?
And is this problem related with bpf_probe_read() exactly?

another question... about secure tracing section in README...

`When Tracee reads information from user programs it is subject to a race condition where the user program might be able to change the arguments after Tracee has read them.`

This line just written from guessing which based on execve problem(bcc #2627), isn't it?

**Comment by yanivagman** [comment]
We added "security_bprm_check" event in addition to execve syscall event.
Maybe you saw the parameter there and not in execve?
Tracing security_bprm_check is an inner kernel security function which works with kernel data structures, thus avoid #2627.

Regarding the second question...
The comment is there not because of #2627, but from other reason.
Consider the case that the user calls "open" (or execve) syscall.
In that case, one of the arguments will be the path to the file to be opened or executed.
This string, that describes the path, lies in userspace memory, controlled by the program in userspace.
Now consider what happens if this program happen to have two threads, where the first thread calls the "open" syscall, and the other thread changes the memory in the address of the path given to open syscall to another value.
Then we got TOCTOU vulnerability, where an attacker can give one path, which Tracee will read (from userspace) when entring the open syscall, and this path can be changed quickly enough before it gets written to kernel memory that will act on this path.

This TOCTOU problem is avoided in Tracee as we also support these two additional events:
"security_file_open" and "security_bprm_check"

Hope this answers your questions

**Comment by jhyang0223** [comment]
> We added "security_bprm_check" event in addition to execve syscall event.
> Maybe you saw the parameter there and not in execve?
> Tracing security_bprm_check is an inner kernel security function which works with kernel data structures, thus avoid #2627.

Below box is my tracee output.
Is this 'security_bprm_check' hook function output?
```
root@logya:/home/jhyang# docker run --name tracee --rm --privileged -v /lib/modules/:/lib/modules/:ro -v /usr/src:/usr/src:ro aquasec/tracee:latest -e execve
TIME(s)        UTS_NAME         MNT_NS       PID_NS       UID    EVENT            COMM             PID    TID    PPID   RET          ARGS
1440           logya            4026531840   4026531836   0      execve           bash             28133  28133  27904  0           [./test [./test]]
1440           logya            4026531840   4026531836   0      execve           test             28133  28133  27904  0           [/bin/ls [/bin/ls]]

```

**Comment by yanivagman** [comment]
No, it's not security_bprm_check event.
Do you run the following test program?

```
#include<stdlib.h>
#include<unistd.h>

int main(int argc, char *argv[])
{
	char *newargv[] = { NULL, NULL };
	char *binpath = "/bin/ls";
	newargv[0] = binpath;
	execve(binpath, newargv, NULL);
}
```

If so, it is indeed strange that you get the arguments themselves.
If you run execsnoop, do you get the arguments as well? 
If you do, I can think of one more explanation - maybe you compiled the program in a way that data section and executable section are placed in on the same segment (this can be tested with readelf -l).

**Comment by jhyang0223** [comment]
I use it as test program and compile command is ```gcc test.c -o test```...
I think it is indeed strange, too...

**Comment by jhyang0223** [comment]
And... Can you answer me about this question...?
> And is this problem related with bpf_probe_read() exactly?

**Comment by yanivagman** [comment]
Yes, indeed strange, but strange in a good way (it's working :-))

Regarding your other question, as far as I understand, the issue is caused because the page where the string is in memory wasn't referenced yet, thus was not fetched by the kernel.
Fetching the page can't happen during the call to bpf_probe_read() as it requires a page fault handler which doesn't exist in the bpf vm context (this last sentence is only my understanding, and may be wrong).
For this reason, the read fails and no arguments get printed.

**Comment by jhyang0223** [comment]
Thank you for your attention to this matter :-)
