### ISSUE TITLE
Investigate if we need `embedded.go` anymore

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#1494]
There was discussion in #1460 about whether or not the top level  `embedded.go` file is still used. It embeds the signatures/rego/helpers.rego file into a variable. Let's investigate if it's used, and if not remove it.

**Comment by grantseltzer** [comment]
Ok I investigated and it is used/needed. As mentioned above it embeds `signatures/rego/helpers.rego`. That contains helper functions which are used across almost all rego signatures. They're used after being loaded via the embedded interface.

**Comment by yanivagman** [comment]
> Ok I investigated and it is used/needed. As mentioned above it embeds `signatures/rego/helpers.rego`. That contains helper functions which are used across almost all rego signatures. They're used after being loaded via the embedded interface.
> 
> ~I just want to confirm that it needs to be at the top level directory.~ it does

So just a small question - why is it located under the tracee(now ebpf) package?

**Comment by danielpacak** [comment]
IMO embedding `helpers.rego` doesn't make much sense for people writing custom signatures in OPA Rego. For example, they might need more helpers than what we provide along with tracee-rules binary distribution.

Probably more useful thing would be to load `helpers.rego` from the same directory where we store default Rego signatures.

Regarding embedded.go, the only reason we placed it in the root of the project was because Go embed package does not support relative paths such as ./../helpers.rego. There are some workarounds to replace path go Go generators, but for the "stabilisation" we wanted to keep it simple without break existing functionality.
