### ISSUE TITLE
Include packaging in the PR workflow

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#1597]
We should test the packaging process of tracee to make it reliable.

**Comment by rafaeldtinoco** [comment]
Thanks @AsafEitani. So, since the package building evolved into something usable by others (@AsafEitani in this case) we should start testing it in PR workflow (at least 1 or 2 flavored packages) OR in a weekly base (cron like) action.

@danielpacak what do you suggest here ? Asaf started using generated packages for some of his tests, should we do cron job like action to test packages generation ?

**Comment by danielpacak** [comment]
For the PR workflow it's probably too much, but we can have a smoke test for packages run on cron schedule. 

Related to that is actually an issue we found out with custom Go signatures that do not work with deb packages (in v0.7.0-rc-1), so IMO we should also extend the smoke tests suite with a test case that is trying to compile external Go signatures and load them. Otherwise we won't be able to catch the following errors:

```
sudo dpkg -i tracee-ebpf_0.7.0-rc_21.10_2203241052-af9e2dc_amd64.deb
sudo dpkg -i tracee-rules_0.7.0-rc_21.10_2203241052-af9e2dc_amd64.deb

git clone https://github.com/danielpacak/tracee-go-signatures.git && cd tracee-go-signatures
mkdir -p dist
GOOS=linux  GOARCH=amd64 go build \
  --buildmode=plugin \
  -o dist/tracee-go-signatures.so \
  export.go \
  stdio_over_socket.go \
  kubernetes_api_connection.go

sudo /usr/bin/tracee-ebpf \
  --output=format:gob \
  --output=option:parse-arguments \
| /usr/bin/tracee-rules \
  --rules-dir /home/vagrant/dev/tracee-go-signatures/dist \
  --input-tracee=file:stdin \
  --input-tracee=format:gob
2022/03/28 06:52:15 error opening plugin /home/vagrant/dev/tracee-go-signatures/dist/tracee-go-signatures.so: plugin.Open("/home/vagrant/dev/tracee-go-signatures/dist/tracee-go-signatures"): plugin was built with a different version of package github.com/aquasecurity/tracee/types/protocol
Loaded 0 signature(s): []
```
