### ISSUE TITLE
Filter Signature Metadata

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#1728]
## Prerequisites

- [ ] This issue is an EPIC issue (add label: EPIC).
- [ ] This issue is an EPIC TASK (add issue to EPIC description).

Select one OR another:

- [x] I'll create a PR to implement this feature (assign to yourself).
- [ ] Someone else should implement this (describe it well).

## Feature description

In order to allow configuring tracee-ebpf filters according to the needs of tracee-rules signatures, signatures should expose a new `Filters` metadata field. This can be used by tracee-rules or any other mediator to determine filter requests to be sent to tracee-ebpf (API in #1726).
If a priority system will be needed, the signature's severity field will be used to determine that priority.
Per event filters will be supported through #1830.

## Additional Information (feature drawings, files, logs, etc)

Draft of the metadata struct:

```
type Operator uint //enum for evaluator types (for example: ==, !=, >, etc.)

type Filter struct {
    field         string
    value        interface{} //this should match the filterType
    operator  Operator
}
```

An example for a filter struct:
`Filter{field: "execve.container", value: true, operator: Equal}`

**Comment by mtcherni95** [comment]
@AsafEitani need to think how we should add the filtering metadata to signatures.

**Comment by AsafEitani** [comment]
Cool!
I got some concerns though:

- Once we move to that method it's all or nothing. You can't have a rule that is using this feature and another that isn't because that will mean either we get nothing from it (all the events will have to get to userspace) or we will lose relevant events for the later signature (because by not using the feature it doesn't have a `Filter` field - so only event relevant to other signature will get to it)
- The suggested struct for it is **very** not comfortable and is unreadable. We should try to come up with something more elegant in my opinion.
- I assume that rego rules won't support this feature - but I'm OK with that because is seems that we are moving away from rego - see #1732 
- There are some filters that are not that easy to set a filter for.
- The conversion of the rules will be manual and hard, some filters are complicated and we will need to find a simple representation for them to be checked in the kernel =(eg. regex filter will have to have a contains, starts or ends filter of some part of the regex filter - `\.+?foo\d+\s\w.+?bar` will have to have some sort of a filter like `contains('foo')\ends('bar')`)

**Comment by NDStrahilevitz** [comment]
@AsafEitani These are valid concerns, i'd like to try and address them because I think they are mostly solvable:

* I think you're onto a valid concern here, but i'd like to point out that actual filter mediation is not done by the signatures themselves (see #1729). The signatures should only declare this filter metadata and let the mediator do the logic of which filters to actually request.
* I think GitHub is somewhat messing up the formatting here, i'll try and fix that. However this struct is only a suggestion, if you or anyone else has a better idea, you're more than welcome to share.
* Rego _should_ be able to support this actually, since we're only declaring metadata. Filtering isn't at all done in the signature itself for this use case.
* Probably true, but could you provide an example?
* Currently the plan is to only send these filters to the existing filter system in tracee-ebpf (which is static and doesn't do regex). So the concern of "how will this actually be filtered" isn't a concern of the signature, the signature simply declares it's ideal filters, and reconciliation of that is handled elsewhere. You could declare these filters, or simply use a simpler version of it to send to tracee-ebpf and complete the filter inside the signature. Alternatively, you could simply ignore this feature for those cases.
