### ISSUE TITLE
[BUG]  Can't compile tracee 0.6.5 locally on Apple M1

### ISSUE THREAD

**Issue by OmerBlechman** [aquasecurity/tracee#1805]
I'm trying to build tracee 0.6.5 locally on my M1 and receiving:

```
/Library/Developer/CommandLineTools/usr/bin/make -C tracee-ebpf mostlyclean dist/tracee-ebpf OUT_DIR=dist && cp -r tracee-ebpf/dist/tracee-ebpf dist
awk: calling undefined function lshift
input record number 1, file
source line number 1
grep: /etc/os-release: No such file or directory
grep: /etc/os-release: No such file or directory
rm -rf dist/tracee-ebpf dist/tracee.bpf dist/tracee.bpf.21_4_0.v0_6_5.o dist/tracee.bpf.core.o dist/tracee.bpf.tar.gz
missing required tool llc
make[1]: *** [check_llc] Error 1
make: *** [dist/tracee-ebpf] Error 2
```

I tried to compile the repo with `make` command.

Can you assist?

**Comment by rafaeldtinoco** [comment]
## This is not a bug, the project is meant to be compiled in on Linux.

OSX builds aren't supported but, because of Docker, you may try:

1) Using the builder helpers (alpine or ubuntu) to build it:

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/7395852/172514862-1d551244-33a7-49c2-b0c6-bf2b516f6e67.png">

OR

* building the container image using docker build files:

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/7395852/172515112-4ebf87b2-416f-4199-999b-8595b950ae51.png">

All the building targets have "make help" AND the building options are described in docs.

I'm closing this since this is not a bug.

**Comment by OmerBlechman** [comment]
@rafaeldtinoco Thanks but I'm working with 0.6.5 version and there is no "Builder" directory in this repo.
I already tried to copy them from "master" branch but then I'm receiving:

```
if [ $? -ne 0 ]; then
/bin/sh: -c: line 1: syntax error: unexpected end of file
make: *** [.check_docker] Error 2
```

**Comment by rafaeldtinoco** [comment]
Version 0.6.5 is not supported in OSX, nor version 0.7.

If you would like to use 0.7 then there is a workaround to have tracee built in OSX, like I explained, but it is unsupported by the project.
