### ISSUE TITLE
[BUG] Use elevated capabilities in new kernels

### ISSUE THREAD

**Issue by AlonZivony** [aquasecurity/tracee#1815]
## Prerequisites

- [ ] This affects latest released version.
- [ ] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [x] Someone else should solve this.

## Bug description

To mitigate the #1803 bug, new kernels capabilities changed in tracee-ebpf to include `CAP_SYS_ADMIN` instead of `CAP_BPF`+`CAP_PERFMON`.
This mitigation resulted that tracee-ebpf in new kernels have much higher capabilities than required, which make it much more exposed to security issues.
To remove the `CAP_SYS_ADMIN` capability, we need a solution so kprobes could be created without any errors.

**Comment by yanivagman** [comment]
More info from @AlonZivony mentioned in #747 :
"The issue here was that some distros didn't work without CAP_SYS_ADMIN event though it should work with their kernel version.
To do this bugfix, the reason for the error in https://github.com/aquasecurity/tracee/issues/1803 should be resolved.
I don't have the time for it right now, so if @cdelzotti want to solve it, it would be great :)"

**Comment by cdelzotti** [comment]
Can I have indications about which distro doesn't work without CAP_SYS_ADMIN in order to reproduce the bug ?

**Comment by AlonZivony** [comment]
From the tests it seems that the `jammy` and `focal` releases didn't work with the new capabilities.
You can try to look more into the tests that failed.

**Comment by rafaeldtinoco** [comment]
Please be aware that, if because of a kernel bug, those distributions aren't able to cope with correct capabilities, then it is what is is. We have to make sure we work in all supported environments with LATEST kernel/env updates (and, hopefully, try to mitigate released environments. This is exactly what BTFHUB is about, for example, as latest kernels provide BTF information, but we wanted to maximize our chances of working in all envs).

**Comment by cdelzotti** [comment]
Okay, I recompiled the kernel on a default Ubuntu Focal with the same kernel version and the bug disappeared. I deducted it was related to Ubuntu itself and bingo : https://patchwork.ozlabs.org/project/ubuntu-kernel/patch/20201126205206.2463398-2-cascardo@canonical.com/

Turns out the Ubuntu Team decided to set the `CONFIG_SECURITY_PERF_EVENTS_RESTRICT` kernel flag for security reasons, meaning that the `/proc/sys/kernel/perf_event_paranoid` should be set to 3 (It was actually set to 4 in my setup) (https://lwn.net/Articles/696236/).

The kernel documentation does mention this `perf_event_paranoid` information :
```
           /proc/sys/kernel/perf_event_paranoid
                  The perf_event_paranoid file can be set to restrict
                  access to the performance counters.

                  2   allow only user-space measurements (default since
                      Linux 4.6).
                  1   allow both kernel and user measurements (default
                      before Linux 4.6).
                  0   allow access to CPU-specific data but not raw
                      tracepoint samples.
                  -1  no restrictions.

                  The existence of the perf_event_paranoid file is the
                  official method for determining if a kernel supports
                  perf_event_open().
```

I tested Tracee with these different value and it seems to work with `CAP_BPF` and `BPF_PERFMON` when running with a `perf_event_paranoid` value <= 3.

Now, I guess I have a choice between creating a PR changing both the capabilities and the documentation to make clear that users should lower their  `perf_event_paranoid` value or leaving Tracee with `CAP_SYS` so that users don't have to change anything in their setup. Which one do you think is the best ?

**Comment by AlonZivony** [comment]
Nice debugging!
I think the default behavior of tracee should be to run, so I think we will need to check this configuration and decide according to it what capabilities are required.
We can leave an alert message or debug message that tracee run with higher capabilities, and to prevent it this configuration should be modified.
