### ISSUE TITLE
[BUG] Capability missing for -c dir:<path>

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#1981]
## Prerequisites

- [x] This affects latest released version.
- [ ] This affects current development tree (origin/HEAD).
- [x] There isn't an issue describing the bug.

Select one OR another:

- [ ] I'm going to create a PR to solve this (assign to yourself).
- [x] Someone else should solve this.

## Bug description

This is how I'm executing tracee (cmdline):
```sudo dist/tracee-ebpf -t e=init_module -c module -c dir:/home/eitani/malware```
This is the error I'm getting:
```2022/07/18 15:02:42 error creating Tracee: error creating output path: mkdir /home/out: permission denied```
## Steps to reproduce

Steps to reproduce the issue:

1. run the above command
2. see the error

## Context

Relevant information about my setup:

* Linux version: 
* Linux kernel version:
* Tracee version (or commit id of your tree):
* LLVM version:
* Golang version:

**Comment by NDStrahilevitz** [comment]
Possibly related: https://github.com/aquasecurity/tracee/pull/1958#issuecomment-1183341217

**Comment by AlonZivony** [comment]
Your error is pretty weird, because it suppose to create the folder `/home/eitani/malware/out`, not `/home/out`.
Might it be bug with the logic of creating the output folder?

**Comment by NDStrahilevitz** [comment]
From currently testing - this doesn't reproduce as late as commit `1224824a63742c0b67aed3a6e431a52341286615` (libbpfgo 0.8.0 update)

**Comment by AlonZivony** [comment]
@yanivagman notice this will be even worst if we change user from `root` in the future.

**Comment by NDStrahilevitz** [comment]
> A possible solution might be creating the directory with the correct permissions before dropping any extra capability. WDYT?

So there are actually two places where we create the dir, first is tracee-ebpf/main.go:232 and pkg/ebpf/tracee.go:395.

So if we run this mkdir before capability dropping, we would need to choose the first and move it. But maybe this should be part of tracee's internal business logic, since we define all captures later in the pipeline go there? I've opened relevant issues on #1990 and #1989

> I think the user should be able to set a directory as he desires IF HE HAS THE RELEVANT PERMISSIONS when starting tracee.

But it's always `root` creating the directory in tracee, that would mean`root` must create those dirs too. Then we need to document this. And when we move users from `root` it would be even worse because now the user can't supply their own path again. Setting up tracee would just get really complex.

Additionally we have many subsystems in tracee requiring file reads from /proc/fs and /sys/fs, for example in #1956. These also require certain privileges for the running user.
