### ISSUE TITLE
Can't trace some system call in multi-thread program

### ISSUE THREAD

**Issue by chae-yc** [aquasecurity/tracee#223]
Hi. I'm studying on research work about system call tracing through eBPF and Tracee is the most suitable tool for my project.
But I have no idea about the reason why this problem happen.

I wrote a simple C code(TargetApp.c) below to see if Tracee can trace all syscalls in the system.
In this code, 16 child processes are forked and each child process executes getpid 62,500 times.

```c
int numOfCallsInLoop = 1000000;    // 1 million
int num_proc = 16;
int i, j, pid;

for(i=0; i<num_proc; ++i){
    pid=fork();
    if(pid == 0){
        for(j=0; j<numOfCallsInLoop/num_proc; ++j){
            syscall(39);    // getpid
        }
        return 0;
    }else if(pid == -1){
        return 1;
    }
}
for(i=0; i<num_proc; ++i){
    wait(NULL);
}
```

Therefore, the total number of getpid syscall is 1 million and I expected that sum of eventCounter and LostEvCounter should be more than 1 million.
However, the number of events shown in Tracee was below, sum of those two value was only **387,569** (=307,235+80,334).
So it was too less than I expected.

![image](https://user-images.githubusercontent.com/29093082/92589055-f1169900-f2d4-11ea-8eb6-a124b440f263.png)

**Test Environment**
Num of Core: 8
OS: Ubuntu 20.04 server 
Kernel: 5.4.0-45-generic

Tracee start command: `sudo ./tracee -e getpid`
(By the way, Tracee don't show any event when I run that TargetApp code after the commit "Handle events parameters types and names using parameters map [915a1ccf12a6008baf5a7d994d7b2a5beee6c513]". So I used the previous version)

**Comment by yanivagman** [comment]
Hi @chae-yc ,

Thanks for opening this issue.
Indeed in master there was a bug that forks (or clones) of a taced process were not traced as well, and this is why it didn't show any event (other than the parent pid events) in master branch.
I pushed a PR for this issue: #224 

I also checked your program, and saw that when the number of events was small (~100,000), there was no issue.
When I changed to 1M events, I reproduced the issue you reported.
I then decided to check with a bigger buffer by running with '-b 4096':
`sudo ./tracee -b 4096 -e getpid`

And indeed no events lost this time!

I suspect there is an issue with the reported number of lost events. 
I'll try to figure this out, but I'm not sure this issue is related to Tracee itself (hopefully it is, and then we can fix it quickly :-) )

As the example you gave calls syscalls in a loop, the buffer will be filled quickly, thus should be big enough. Please use a bigger buffer like suggested above if you need to support these kind of scenarios (bare in mind this means a more memory consumption by Tracee)

**Comment by yanivagman** [comment]
Regarding the lost events...

Waiting few extra seconds (~10sec) after all events were printed (using the default buffer, without '-b 4096'), I can see that all 1M events are either printed (~350K events) or lost (~650K events). If I exit Tracee before waiting this time, there are missing lost events like reported. So, there is no bug here for the lost events count...

Tracee gets the lost events count from gobpf (using lost channel), and this, in turn, comes from the kernel - either one of these may cause this delay of reporting lost events.
