### ISSUE TITLE
`./tester.sh` issues

### ISSUE THREAD

**Issue by 06kellyjac** [aquasecurity/tracee#2328]
Since I'm building tracee in a hermetic environment I have to compile the integration tests & run them later in an ephemeral VM.

https://github.com/NixOS/nixpkgs/blob/07ff3b173769f87c7c84b9b827f4a1f2dab63a91/nixos/tests/tracee.nix#L47

The fact that the integration tests need `./tester.sh` in the PWD is quite a pain. I resolve this by forcing it to look at a fixed path (e.g. `/usr/bin/tester.sh`)
It would be better if it could be substituted with an env var.

While diving through the code I also noticed that `TRC_BIN` no longer exists because tracee is being embedded. It feels a bit weird that the integration tests can't be pointed at an existing tracee binary.
If you're committed to this embedding could you not also embed the shellscript or a small go binary and remove the need to bring `./tester.sh` along for the ride?

---

Also I'm finding that it's inheriting no env vars so can't find `docker` or `ls`

When I edit the script to just run `/nix/store/v0nach9fy0sfd5wr5r6x785wq7sxx6gg-busybox-1.35.0/bin/env >&2; exit 1`

```
PWD=/tmp
SHLVL=1
_=/nix/store/v0nach9fy0sfd5wr5r6x785wq7sxx6gg-busybox-1.35.0/bin/env
```

This is something I can resolve by giving the script a PATH var or hardcoding the things like `/xyz/abc/ls` but not ideal

(These are the changes I made in the end: https://github.com/06kellyjac/nixpkgs/commit/9b9d46ed0e5a0de0ad4d2637f5795eb359772ce4#diff-3591fa1ddd1e65596cdcffb43b6e683498030a1b8d4599346f9ca1f55f5bfdfa)

**Comment by grantseltzer** [comment]
Hey @06kellyjac, thanks for bringing this up. I was completely unaware of this implication when adding this tester shell script. Let me make sure I understand what you're saying and what can be done though. Can you tell me if the following is accurate?

1) Since the integration tests have a relative path to `tester.sh` this causes an issue for you since you're compiling the integration tests, placing them somewhere, and running them. This means that you'd have to move the script alongside the compiled test binary. which is understandably a nuisance. 

The solution for this is to do one of the following:
- Embed the shell script
- Have an optional environment variable for specifying a different path to the script

I'm happy to embed the script, I think this change makes perfect sense.

2) The shell script doesn't have access to the parent proc's environment variables.

This is actually a very easy fix. The `syscall.ProcAttr` argument to `ForkExec` has a field for this. I will gladly handle this as part of the same PR as above.

**Comment by 06kellyjac** [comment]
Thanks for your time and understanding. Yes, thats pretty much the gist of it.
Im not 100% sure if its looking relative to the unpacked Tracee (/tmp) or in PWD of where the integration tests were executed from (I think this is more likely)
Your suggestions should resolve the issue

(If it's the latter & `go test` goes into each dir to launch tests but compiling the tests and running them later behaves differently maybe upstream should make some changes?...)

Also I think having the ability to provide an existing tracee binary for testing is pretty important. If TRC_BIN could be re added as an option thatd be great. & ideally a way to skip embedding tracee if you're going to bring your own

**Comment by grantseltzer** [comment]
Sounds great. I can write up issues and try to tackle them this upcoming
week. They're all pretty quick fixes.

**Comment by grantseltzer** [comment]
I've opened #2330 #2331 #2332 to describe the issues separately, going to close this accordingly.
