### ISSUE TITLE
[BUG] NONCORE v4.19 is broken

### ISSUE THREAD

**Issue by rafaeldtinoco** [aquasecurity/tracee#2400]
## Bug description

Looks like v4.19 NONCORE (recently added to our tests, as a runner) does not work. A run with errors can be found here: https://github.com/aquasecurity/tracee/actions/runs/3568848015/jobs/5998367170

```
libbpf: Error in bpf_create_map_xattr(sys_enter_init_tail):ERROR: strerror_r(-524)=22(-524). Retrying without BTF.
libbpf: Error in bpf_create_map_xattr(sys_enter_submit_tail):ERROR: strerror_r(-524)=22(-524). Retrying without BTF.
libbpf: Error in bpf_create_map_xattr(sys_enter_tails):ERROR: strerror_r(-524)=22(-524). Retrying without BTF.
libbpf: Error in bpf_create_map_xattr(sys_exit_init_tail):ERROR: strerror_r(-524)=22(-524). Retrying without BTF.
libbpf: Error in bpf_create_map_xattr(sys_exit_submit_tail):ERROR: strerror_r(-524)=22(-524). Retrying without BTF.
libbpf: Error in bpf_create_map_xattr(sys_exit_tails):ERROR: strerror_r(-524)=22(-524). Retrying without BTF.
libbpf: Error in bpf_create_map_xattr(prog_array_tp):ERROR: strerror_r(-524)=22(-524). Retrying without BTF.
libbpf: Error in bpf_create_map_xattr(prog_array):ERROR: strerror_r(-524)=22(-524). Retrying without BTF.
libbpf: prog 'tracepoint__sched__sched_process_exec': BPF program load failed: Argument list too long
libbpf: prog 'tracepoint__sched__sched_process_exec': failed to load: -7
libbpf: failed to load object '/tmp/tracee/tracee.bpf.4_19_265-0419265-generic..o'
{"level":"fatal","ts":1669672334.7503476,"msg":"app","error":"error initializing Tracee: failed to load BPF object: argument list too long"}
```

**Comment by yanivagman** [comment]
This regression was caused by two changes introduced recently.
The problem is that the instruction count limit is reached for both sched_process_exec and security_file_mprotect programs. This is mainly because path string extraction was added to both, which adds a lot of instructions.

The PRs that introduced this regression are:
1. https://github.com/aquasecurity/tracee/pull/2339
2. https://github.com/aquasecurity/tracee/pull/2216

@roikol @AlonZivony FYI, we will need to find a way to either reduce the instruction count for these programs or remove these changes.

**Comment by geyslan** [comment]
Would it be feasible to split those programs and tail call them?

**Comment by yanivagman** [comment]
> Would it be feasible to split those programs and tail call them?

That's one possible solution, yes

**Comment by AlonZivony** [comment]
Created sub-issue - #2419

**Comment by AlonZivony** [comment]
All of the subtasks are completed and all tests work.
I close this issue as completed.
