### ISSUE TITLE
Add `quiet` option to `tracee-rules`

### ISSUE THREAD

**Issue by tamirkiviti13** [aquasecurity/tracee#2532]
When `tracee-rules` command starts it prints to the stdout the following line:
`Loaded [X] signature(s): [...]`

I would like to have a flag that quiets this print (maybe `-q`, `--quiet`)

**Comment by NDStrahilevitz** [comment]
@yanivagman @geyslan Maybe this should just be a debug message with the logger WDYT?

**Comment by itaysk** [comment]
Agree, it should not be always printed. Also it's the only thing that's being directly printed directly to terminal (event are printed in a testable function that get's `os.Stdout` as argument). Since we are going to unify tracee-ebpf and tracee-rules, let's consider what the behavior should be there. In that case the `table` output format is assumes to be human readable and is allowed to print these kind of things (for example, summaries). but all other outputs are assumes to be machine readable and are only allowed to print out events.

**Comment by geyslan** [comment]
@josedonizetti what do you think of just changing the `Loaded ...` to `logger.Info()`?

**Comment by josedonizetti** [comment]
@itaysk This message is not shown on the new tracee binary. At least for now, the user must explicitly pass which events to load, so I considered we didn't need a message to inform how many were loaded, if you pass `event=anti_debugging,disk_mount`, you know there are two loaded. If one of those doesn't exist, it will error and not start. 

@geyslan for the current `tracee-rules` I don't mind using `logger`

**Comment by geyslan** [comment]
Alright, after analysis I realized that `tracee-rules` doesn't have the log and output options flags that already work in the `tracee` new binary. However, changing this print to `logger.Info()` would work using the old logger mechanism which sets the its level through env vars (to be deprecated https://github.com/aquasecurity/tracee/issues/2475).

In the meantime, the `Loaded ...` message can be silenced by running: `TRACEE_LOGGER_LVL=warn ./dist/tracee-rules ...`
