### ISSUE TITLE
Expose events documentation

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#2686]
Some of Tracee's events are already [documented](https://github.com/aquasecurity/tracee/tree/main/docs/contributing/events), however, this documentation is not exposed in the docs page.
Let's expose them as a new tab in the documentation page.

**Comment by sassukeuchiha** [comment]
Hey @yanivagman can I work on this one?

**Comment by yanivagman** [comment]
@sassukeuchiha for sure!

**Comment by yanivagman** [comment]
Done #2695

**Comment by itaysk** [comment]
It added under "contributing" but this a user-facing documentation. I'm reopening this with intent to move it under more appropriate section.
Also I think it will be very hard to maintain the list of all current and future events in the global navigation, and also hard for the user to navigate hundreds of items in a sidebar, so that can be fixed in the same PR as well.

@sassukeuchiha - Thanks for your contribution! I'm just pinging you as FYI in case you want to take it again. If not, all good, your PR already improved things a bit.

**Comment by sassukeuchiha** [comment]
Yes @itaysk I would love to work on this further .

**Comment by rafaeldtinoco** [comment]
@AsafEitani quick question about this one, I remember you showed us ChatGPT helping us in documenting the events given a format. With what Itay just said, I also believe it will be hard to keep documentation updated unless it is automatically generated from the event code itself. WDYT ?

**Comment by AsafEitani** [comment]
So I used ChatGPT to create the documentation by providing it the format and the event definition in events.go.
I just copied and pasted the code and it was able to generate a pretty accurate description of everything as we relay on either syscalls/kprobes/tracepoints, which are publicly documented.
I recommend using it to provide the draft and then manually edit it if you need.
You can also request certain information when writing the request, like specifying how you can use the event, and ChatGPT will insert it in the roght location.

**Comment by rafaeldtinoco** [comment]
@AsafEitani thanks for the idea. I have implemented something similar to what you described at https://github.com/aquasecurity/tracee/pull/2792. I have also prepared it for generating documents for other types of events (security, network, uprobes, etc) based on the probe type and the eBPF source code (will do this in the next milestone(s) as time allows). Thanks for the suggestion.

**Comment by yanivagman** [comment]
Done as part of documentation restructure for v0.12.0 release
