### ISSUE TITLE
Scopes renaming to set of filters and policies

### ISSUE THREAD

**Issue by geyslan** [aquasecurity/tracee#2727]
- [ ] In documentation, Scopes must be changed to **Sets of Filters**.
- [ ] When the context of a scope is higher (e.g. event_context_t), it must be renamed to policies.
- [ ] When related to internal computation (e.g. task_info_t), it should remain as it is.

**Comment by itaysk** [comment]
are there also plans to change the flags / code accordingly? (for example --trace to --filter)

**Comment by yanivagman** [comment]
> are there also plans to change the flags / code accordingly? (for example --trace to --filter)

We had this debate in the past. I even suggested to use `--filter` (https://github.com/aquasecurity/tracee/issues/377) but for a reason I can't remember, we chose to use `--trace`. I'm still in favor of `--filter` since it describes better the usage of this flag, so I don't mind if we choose to change it.

**Comment by josedonizetti** [comment]
+1 for `--filter`, and the new binary is a great moment to change it

**Comment by geyslan** [comment]
+1 for `--filter`.

**Comment by yanivagman** [comment]
Closing in favor of #2665
