### ISSUE TITLE
execve nil argv, envp

### ISSUE THREAD

**Issue by OriGlassman** [aquasecurity/tracee#2847]
## Description
execve that fails seems to return with nil argv and envp, even though they aren't really empty.

![image](https://user-images.githubusercontent.com/39296766/224556452-4bc46a2d-504c-4a9f-8b8d-1732e2962577.png)

## Output of `tracee -v`:

```
Tracee version "v0.12.0-16-ge01881a2"
```

## Output of `uname -a`:

```
Linux Ori-Glassman 5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yanivagman** [comment]
This is the expected behavior for failed execve.
We submit execve events on syscall entry since after execve replaces the binary image, pointers become invalid, and this include the argv and envp pointers. Only for failed exec we ALSO submit the event on syscall exit, so it is possible to see the reason for failure through the return code. So if you look one line above the failed exec line in the output, you will be able to see the matching argv and envp pointers.
