### ISSUE TITLE
print_mem_dump error on multiple symbols

### ISSUE THREAD

**Issue by AsafEitani** [aquasecurity/tracee#2993]
## Description

When tracee-ebpf is run like so:
`sudo dist/tracee-ebpf -f e=print_mem_dump -f print_mem_dump.args.symbol_name=execve,kill`
to print the memory of execve and kill symbols the following error is displayed:
```
TIME             UID    COMM             PID     TID     RET              EVENT                     ARGS
{"level":"error","ts":1681140625.945699,"msg":"Error processing event","event":"print_mem_dump","error":"ebpf.(*Tracee).processTriggeredEvent: failed to apply invoke context on print_mem_dump event: no event context with id 1"}
{"level":"error","ts":1681140625.9457588,"msg":"Tracee encountered an error","error":"ebpf.(*Tracee).processTriggeredEvent: failed to apply invoke context on print_mem_dump event: no event context with id 1"}
02:00:00:000000  0                       0       0       0                print_mem_dump            bytes: [15 31 68 0 0 85 72 137 229 65 84 83 72 139 95 96 76 139 103 104 72 139 127 112 232 163 173 0 0 73 137 217 76 137 225 69 49 192 106 0 72 137 198 49 210 191 156 255 255 255 232 137 251 255 255 72 141 101 240 91 72 152 65 92 93 195 204 204 204 204 102 46 15 31 132 0 0 0 0 0 15 31 68 0 0 85 72 137 229 65 84 83 72 139 95 96 76 139 103 104 72 139 127 112 232 83 173 0 0 73 137 217 76 137 225 186 1 0 0 0 106 0 72 137 198 65 184], address: 0xffffffff8e18cc40, length: 127, caller_context_id: 1, arch: x86_64, symbol_name: __x64_sys_execve, symbol_owner: system

```

## Output of `tracee -v`:

```
Tracee version "v0.13.1-10-g90f56d07"
```

## Output of `uname -a`:

```
Linux ubuntu 5.15.0-50-generic #56~20.04.1-Ubuntu SMP Tue Sep 27 15:51:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

## Additional details 

It seems that this if statement should be true:
https://github.com/aquasecurity/tracee/blob/main/pkg/ebpf/events_processor.go#L369

But it isn't...

**Comment by NDStrahilevitz** [comment]
Ok here's what's going on, for each argument value in `symbol_name` or `address` we call a trigger for a memDump using THE SAME context handle that we generate at the start of the trigger call (https://github.com/aquasecurity/tracee/blob/main/pkg/ebpf/tracee.go#L1685).
In your example we provided two symbols, triggering two mem dumps, but using only one context id. On using a context id it is deleted (see https://github.com/aquasecurity/tracee/blob/main/pkg/events/trigger/context.go#L52) from the context map. 

So to fix we need to store a context for each trigger call, instead of one context for all trigger calls in the request.
Additionally we should document in the trigger context interface that the same ID can't be reused in one tracee run, so each apply call must have a store call preceding it.
