### ISSUE TITLE
Separate control plane buffer

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#3086]
Some events are essential for tracee's functionality of tracking processes and containers. However in the case we trace events that have a high frequency (such as `security_file_open`), we add the probability of lost events, and losing these events. As such these events should have their own buffer in order to reduce their chance of loss.

Some design questions:
1. What should be the size of such a buffer?
2. Should the events be double submitted (keep the current buffer submission) or moved exclusively to the priority buffer?
3. If we choose the latter above, how can we synchronize with relation to the perf buffer (move event sorting from feature flag to always working?)

**Comment by rafaeldtinoco** [comment]
Using generic computation terms to think about the issue:

Situation:

We have a serial communication, with multiple data packets (events), that are or should be ordered, that differ in hierarchy, AND are interdependent among themselves.

Problem:

Some data packets (events) are way more important than others and dictate program behavior. When in the same serial channel, they compete for channel buffers and might get discarded.

Ideas:

1. To maximize the throughput by having multiple parallel buses. That would also incur in having more userland processing (multiple routines/threads, one per serial channel). This would also cause overhead (of having to deal with jittering among the data packets (events), each of them arriving at each channel in an out-of-order fashion).

> Similar problem solved by LACP, MLPP, HDLC Multilink, VRRP, etc (as inspiration). Most common solution is to hash specific flows to each channel (but then the flows don't depend on each other like our case). Likely a NO for our case.

2. Splitting high frequency data packets (events) into other serial channel (multiplexing). If the endpoint receiving the data packets (userland) didn't need to correlate the packets (events) then it would be a no-brainer. Since it does, then we have to think of some things:

  2.1. High frequency events would always arrive first (need to be buffered).
  2.2. Sequence number to keep ordering AND sync (of high events vs. normal) is needed. TOD (monotonic time of the day) would NOT be enough (because of the same issue solved by our "sorting by CPU ticks" code of the sorting feature).
  2.3. To hold the low priority channel events while picking high priority event from queue.
  2.4. Discard kept events from high priority queue.

> In this case this other channel would work like a QOS channel but we would have to take care of buffering and ordering (and re-ordering when mounting both buses into a single view).

3. Duplicating high frequency data packet so that the high priority packets are more likely to be received and processed by the other bus end (userland). 

  3.1. By splitting the concept of such high priority events into "being an event" and "being a signal", we can always guarantee the "signal" (or close) and live with the fact that the "event" can be lost.
  3.2. We don't need to keep sequence numbers and/or sync among the different events from the two (or more) different buses (channels).
  3.3. We don't need to hold/queue data packets (events) and/or further processing for deletion.
  3.4. The only downside is to "duplicate" an event (memory consumption, CPU cycles for duplicates) which, at least for the original need (use the events as signals for an internal operation) will not be much.

> In this case, the second channel ressembles a "validity" wire when doing a data bus transfer, for example. Instead of using it to understand when a packet begins and ends, we use it for internal processing.

So I'm in favor of my (3) item which is actually duplicating the events (at least until we have another need not do that, considering the pros/cons in between 2 and 3). The (3) item, duplicating events, is the one with more pros for our case, I believe.

**Comment by NDStrahilevitz** [comment]
Thanks for the detailed analysis @rafaeldtinoco.

>So I'm in favor of my (3) item which is actually duplicating the events (at least until we have another need not do that, considering the pros/cons in between 2 and 3). The (3) item, duplicating events, is the one with more pros for our case, I believe.

So if we go with 3 there are some implementation questions that we can raise:
1. Is the "signal" buffer passing the same event type of the events buffer? Maybe we should use a new "signal" event struct. I think for signals only the events arguments would actually be relevant for a signal and all the context would be redundant but i'm not sure if i'm correct on that assumption.
2. If we use a separate signal type, maybe a separate ebpf program attach should be used for signals, in order not to mix logic with the event ebpf program? The pro is that if we're not tracing one of the signals as events we can have only the "simpler" signal programs attached, but if we trace both then there's the overhead of two programs.

@yanivagman any comments from your end?

**Comment by yanivagman** [comment]
Good points @NDStrahilevitz @rafaeldtinoco 
I'm also in favor of option (3).
Currently the "control plane" events include sched_process_exec/fork/exit (process lifecycle), cgroup_mkdir, cgroup_rmdir (container lifecycle) - did I miss any? 
The frequency of these events should be low relative to other events in the system, thus I think we should be good with duplicating the events to two different buffers.
I wouldn't call this buffer "priority events buffer" though, since priority should probably be set by the user. So it is more of a "control plane" buffer IMO.


> 1. Is the "signal" buffer passing the same event type of the events buffer? Maybe we should use a new "signal" event struct. I think for signals only the events arguments would actually be relevant for a signal and all the context would be redundant but i'm not sure if i'm correct on that assumption.

Good point. Since we duplicate the event, we may be able to remove any redundant information such as the context in the "control plane" buffer.


> 2. If we use a separate signal type, maybe a separate ebpf program attach should be used for signals, in order not to mix logic with the event ebpf program? The pro is that if we're not tracing one of the signals as events we can have only the "simpler" signal programs attached, but if we trace both then there's the overhead of two programs.

I'm also in favor of doing this seperation. Makes sense.

**Comment by yanivagman** [comment]
We can also short circuit things in the control plane. Probably there is no need to go through the events pipeline to update internal data structures. The processing of such messages can happen right after receving them in userspace.

**Comment by rafaeldtinoco** [comment]
> Can you please explain what you mean by
> 
> > Most common solution is to hash specific flows to each channel (but then the flows don't depend on each other like our case). Likely a NO for our case.

Sure. I picked the "network bonding" as a model for load distribution. There are multiple ways a link aggregation might be done (round-robin, active-backup, XOR, broadcast or LACP). In our case, if, just as a matter of exercise, we consider one of our event channels as a "network path equivalent", and each of our events a "data packet", then there could be multiple ways of splitting the "data" into multiple "paths".

With bonding, we could use "round-robin" (send events randomly in 2 or more paths), XOR (pick a characteristic of packet metadata (or event context), like src and/or destination (mac and/or IP addresses) and XOR to decide which path to take) OR use something like Ether Channel (or 802.3ad proto).

1. hashing (XOR) would make the same SRC mac address, or same SRC IP, or same DST IP to always use the same path. So in our case that might not work. It is like we pick a metadata (context) from our packet (event) like UID and always send in the same channel (it won't balance the channel's throughput). that would, for sure, maximize overall throughput (considering data flows into multiple channels) but does not solve our problem (unless we do things such as "each container events go to one channel", but then we would have to check if that is "ok", considering the events interdependency).

2. ether-channel: it is pretty much considering the 2, 4 or 8 paths as a single path (logically), deciding different aggregation groups (where to keep net packets by what characteristics), but reconstructing the "single path" idea at the end in an ordered fashion (this would require us to keep track of a timestamp per event and sorting all events at the end, buffering at the end of these multiple channels so we have time to order packets, CPU time, etc).

Those 2 examples would be for the case (2) @NDStrahilevitz has brought. For the case (3) I used a different analogy (a parallel bus using signaling pins, but I think I made my point there).

Hope it clarifies =D my "triping"

**Comment by rafaeldtinoco** [comment]
> > 1. Is the "signal" buffer passing the same event type of the events buffer? Maybe we should use a new "signal" event struct. I think for signals only the events arguments would actually be relevant for a signal and all the context would be redundant but i'm not sure if i'm correct on that assumption.
> 
> Good point. Since we duplicate the event, we may be able to remove any redundant information such as the context in the "control plane" buffer.

Agreed! I thought about that as well. If you check the network capture channel, I only duplicate the entire event context structure because I wanted to use the same functions from the "regular pipeline" to decode/parse/enrich my network capture events. But, in this case, we don't need the same pipeline logic, so we can create smoother events.
