### ISSUE TITLE
errors when using builtin.so for external sigs

### ISSUE THREAD

**Issue by roikol** [aquasecurity/tracee#3109]
## Description

when using builtin.so in order to load external signatures, and starting `tracee` (unified binary) - there are a lot of error messages.

the messages are all the same:
`{"level":"error","ts":1684250110.725621,"msg":"Failed to add event definition","error":"events.(*eventDefinitions).Add: error event name already exist: "}`

![image](https://github.com/aquasecurity/tracee/assets/17714090/37e04c07-2280-4fe2-85be-59520b437bcd)

## Output of `tracee version`:

```
(paste your output here)
```

Tracee version: "v0.14.2"

**Comment by NDStrahilevitz** [comment]
This is likely because the `EventName` field wasn't set in those signatures metadata. As you can see from the error the event name which already exists is ` ` representing the empty string, which would be the default value given here.
So I'm not sure this is a bug but maybe a better error message could be helpful.
