### ISSUE TITLE
Filter by UID

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#312]
extend the current `--trace` flag to support in-kernel filtering by user id, like so: `--trace uid:1001`

**Comment by grantseltzer** [comment]
What are your thoughts on having a flag for `--uid` instead of lumping it in on `--trace`?

The way I understand it, there are two 'modes'. Container mode, and process mode (or non-container mode). UID filtering is applicable for both modes so wouldn't affect that. There are also other filters that could be added that would be applicable in either mode. Some examples would be GID, PPID, particular namespaces, or cgroups (not sure how tracee handles k8s pods at the moment).

Here's my idea for a more intuitive design and am happy to iterate based on your thoughts:

- Remove the `--trace` flag.
- For each value a user wants to filter by, they specify it with a corresponding flag.
  - `--uid`, `--gid` (both default to all)
  - `--pid`, `--ppid` (both default to all, can also specify new, list of pids, or specify multiple times)
  - `--container` (default to all, specific container ID, multiple IDs, 'new' or 'all')
  - `--ns`, `--cgroup` 
  - ...
- All of the specified filters would be logical "AND"'ed together. For example `tracee --pid=new --uid=1000` would only produce new processes with uid 1000.
- The 'mode' (container/process) can be implied by the use of flags. If `--container='___'` is specified then the mode will be container and the `pid`/`ppid` flags (if specified) will be ignored. Applicable filter flags would be honored. 

Alternatively I can see:

- Adding a `--filter` flag
  - Can be specified any number of times.
  - Arguments would be of the form `<filter>:<value>` (example: `pid:56132`, `pid:new`, `uid:0`, `gid:10`)

**Comment by yanivagman** [comment]
Hi @grantseltzer,

We had a long discussion in #221 about some of the things you wrote here.
In the end, there are different ways to tackle this, and we need to think about a clean and intuitive UX,
but it's probably also a matter of taste...

Like you said, we currently have "modes" of operation.
We can consider these "modes" as filters, but I think that what makes them different from other filters, is that they represent the traced entity(ies) or workload(s), which dynamically change over time, and as such also have the "new" flag.
Opposed to other filters which can be logical "AND"ed together, these modes are also usually mutual exclusive - there is no sense in telling tracee to filter both new processes and all processes, or all processes and newly created (or specific) containers. 

Now comes the question that we still need to discuss - do we think that it's a good idea to integrate the "--trace" flag in our new filters design? I still don't have a clear opinion about this.
I think that there are some good reasons to keep these separated (like the mutual exclusiveness and "new" flag discussed above), but I also understand the rational in making things more intuitive and simple.

Getting back to the original issue, I think that uid filtering shouldn't be part of the "--trace" for the reasons described above.
I think that this can be implemented with
`-f <field name>=<value1>[,<value2>...] / --filter <field name>=<value>[,<value2>...]`
As @lizrice suggested in #29 
We can also combine multiple filters under the same `--filter` flag by putting a separator like:
--filter <field name 1>=<value>[,<value2>...]; <field name 2>=<value>[,<value2>...]

Using "=" instead of ":" also has the advantage of expanding the filters with ">" and "<" in the future

**Comment by grantseltzer** [comment]
Hi @yanivagman! 

Good point on the logical separation between modes and filters. When it comes to user interfaces for complex systems like tracee I like to think "What is the user's intent" vs "What is an implementation detail". Intuitive interfaces I believe are designed around user intent. The user wants to trace container events, not to run tracee in container mode. With that in mind I like the idea of implying the mode by what filters the user specifies. 

A couple examples of tools that have each filters in their own flags are `strace`, `journalctl`, `kubectl`

An example of a tool that have a 'filters' flag include `docker events`

My vote is for separate filter flags (i.e. `--uid`, `--pid`) but I don't have a strong objection towards `--filter` flag

**Comment by yanivagman** [comment]
@grantseltzer I agree that we shouldn't think about implementation, but user first, and this is exactly what guided us in #221 discussion.
@itaysk made some good arguments in favor of using the --trace option:

> I didn't think that providing multiple flags each with a diverse set of options and then expecting the user to understand how the different flags and options work or doesn't work together, is a good approach, so I proposed to make this a single flag which naturally reflects that the user need to choose one option, and makes extending this flag in the future simpler.

> I think it's easier to remember that there is one flag that controls the scope of the trace rather then having multiple flags. Also it's easier to discover all the scope related options in one place (when browsing the --help). Also I think it's intuitively conveying the exclusivity rules, without having to read the docs or to encounter a validation error.

**Comment by itaysk** [comment]
Good discussion. There are 2 questions here: 1) trace mode vs filter 2) filter flag vs individual flags

trace mode vs filter, here's my summary:
- trace modes are mutually exclusive, filters are not
- trace modes may require different ways to attach to the target, filters operate on the already normalized and collected data. 
- trace mode extends the functionality of tracee, filters may be applied today by external tooling (e.g pipe to jq). we should also be careful in the future not to feature creep into reimplementing such extensive tools in tracee.
- just a note: this might be related to our plans to extend and improve the signature detection engine.

About the --filter vs flags: Perhaps this is a subjective matter as Yaniv pointed out. I think that for us it's better not to overload the UX with many flags that configure the same configuration. It will be easier to discover, use, remember, etc.

We actually discussed this before opening this issue and saw that it leads to a broader discussion so in order to make this implementable by an external contributor under reasonable effort, we bolted the UID filter on the existing --trace flag, with plans to improve it later. Your point about UID being useful in different modes is spot on, so if you want to instead implement this as a --filter, I think that's fine as well pending @yanivagman's ok.

**Comment by yanivagman** [comment]
For now, let's keep the "--trace" flag as is. We may reconsider integrating it with filters in the future if we see fit.

Regarding the second question (separate flags vs --filter flag), I'm find with both options, we just need to make sure we understand the pros and cons of each.

I agree with Grant that it is more intuitive (and requires less typing) to just use separate flags.
I also understand what Itay says that it may be easier to discover using the --filter flag, although I'm not sure about easier to use and remember, as with --filter you also need to remember the filter field name (e.g. 'uid') and type it.

Two more points to consider: 
1. we only talked about "filter in", but "filter out" option should also be considered when thinking about the design as it is usefull as well. If we choose to use the --filter flag, we can also have "--filter-out", or maybe adding a prefix for the filter field name (e.g. --no-uid). If we choose having separate flags for each filter, this will double the amount of required flags.
2. Other than having the equal filter, we should also consider having "bigger than" and "less than" filters in the future (an example use case may be "filter negative return value" or "filter uids bigger than 0"). As using "--filter" flag receives a string, this can be implemented by having ">", "<" as well as "=" (e.g. "--filter uid>0")

**Comment by yanivagman** [comment]
@grantseltzer do you plan to work on the ">" "<" uid filtering,
or should I close this issue for now?

**Comment by grantseltzer** [comment]
@yanivagman I'm half way through a diff for filter operators, i'll have time to work on it Thursday and Friday so will submit it probably over the weekend. I'll open a new issue for it so we can close this one.

**Comment by grantseltzer** [comment]
Created #328
