### ISSUE TITLE
simplify docker run command

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#3156]
the reference docker run command include some redundant options that could be simplified

```
docker run \
  --name tracee --rm -it \
  --pid=host --cgroupns=host --privileged \
  -v /etc/os-release:/etc/os-release-host:ro \
  -v /boot/config-$(uname -r):/boot/config-$(uname -r):ro \
  -e LIBBPFGO_OSRELEASE_FILE=/etc/os-release-host \
  aquasec/tracee:$(uname -m)
```

**Comment by rafaeldtinoco** [comment]
Be aware that trying to guess what "os release" the host has might be the same as improving the OSinfo package from libbpfgo (which, IMO, should also be removed from libbpfgo and moved into tracee) not to depend on os-release file. 

Also, note that.. a kernel called "5.4.0-1029-aws", might exist both for Bionic AND Focal, for example (thus to understand which version the host has, since their BTF might be different).
