### ISSUE TITLE
Tracee errors/warns on gke 

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#3397]
We see a few errors and warns when tracee is booting at GKE, this is a bit misleading to the user, because seems like tracee is not working, though it is but it didn't load a few probes. Can we investigate why the error/warns below happen? Can we fix them? If not, can we change the log level or message so the user know tracee is not broken.

```
 {"level":"error","ts":1691077966.0057297,"msg":"Event canceled because of missing kernel symbol dependency","missing symbols":["sys_call_table"],"event":"print_syscall_table"} 
{"level":"warn","ts":1691077991.8121207,"msg":"libbpf: prog 'trace_vfs_writev': failed to create kprobe 'vfs_writev+0x0' perf event: No such file or directory"} 
{"level":"warn","ts":1691077991.829119,"msg":"libbpf: prog 'trace_ret_vfs_writev': failed to create kretprobe 'vfs_writev+0x0' perf event: No such file or
```

**Comment by josedonizetti** [comment]
@AlonZivony  would you be able to look into this one?

**Comment by AlonZivony** [comment]
OK, so the error message is expected - the `sys_call_table` symbol is a data segment symbol.
The GKE I worked with was compiled without the `CONFIG_KALLSYMS_ALL` flag, which result that only the text segement symbols (aka the functions symbols) are saved there.
Hence, the syscall table symbol which is a global array is not kept there. Because it is a dependency of the `print_syscall_table` event, it fails to load.
The problem here is that it is not trivial to have the syscall table address without it being in the kallsyms file. We need to think how to address this issue.

The two other warnings I am not sure about, maybe they are the result of the fail in the `print_syscall_table` event somehow. We need to see if they will be solved by a fix we do to the event.

**Comment by AlonZivony** [comment]
For reference, I add a link to previous similar problem we had with GKE I solved by changing the used symbol from global struct to a function:
#3380

**Comment by geyslan** [comment]
> The problem here is that it is not trivial to have the syscall table address without it being in the kallsyms file. We need to think how to address this issue.

It's not trivial indeed. I didn't find any assignment of sys_call_table to be read later from other accessible  object. What I found was that in GKE we have symbol for `arch_syscall_addr`:

```
root@cs-1075887186839-default:/home/geyslan# grep arch_syscall_addr /proc/kallsyms
ffffffff89bb33e3 W arch_syscall_addr
```

It would be necessary to peek at its return `arch_syscall_addr(0)`. WDYT?

**Comment by geyslan** [comment]
In hindsight it's not feasible since it returns the address of the function (first element), not of the sys_call_table itself. 😿 

```c
unsigned long __init __weak arch_syscall_addr(int nr)
{
	return (unsigned long)sys_call_table[nr];
}
```

**Comment by AlonZivony** [comment]
I know that rootkits have a method of gaining the address without the kallsyms.
I will try to look for it and will send it here.

**Comment by itaysk** [comment]
can you please explain what is the `print_syscall_table` event and why it's in the default policy?

**Comment by geyslan** [comment]
It's an internal event which provide syscall addresses to the `hooked_syscalls` one.
