### ISSUE TITLE
Failed to run tracee on Kali linux

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#342]
Kali linux (and other ditros?) has it's headers files seperated between /lib/modules/KERN_RELEASE/build for headers generated during build and /lib/modules/KERN_RELEASE/source for all other includes.
As a result, we fail to compile the bpf code as the headers are not where we expect them to be

**Comment by itaysk** [comment]
I think we will keep finding more and more variations of how distros and custom setups handle kernel headers in their own conventional way. kernel headers are the only value we still expect the user to provide, but we do make an effort to guess it's default value for most  environments. The answer to all of the kernel headers issues should be - you should provide the kernel headers with the KERN_SRC variable. But in this case the user can't do it because it's split in multiple locations. 

So here's a suggestion how to address this in two separate steps:
1. change the KERN_SRC var to accept multiple values. and include all of the values in the compilation. If the user wants to source the headers from 10 different locations just set the var appropriately.
2. change the default value for the var to consider how kali does it.

**Comment by yanivagman** [comment]
This is a good suggestion, but I think we should handle this specific case automatically.
I saw this split when I did the move from bcc to libbpf, and took a note that we should complete this when we will get to the stabilization stage, which is now.
This case is relevant for several distributions: debian (and kali), suse, opensuse, and it is handled by bcc:
https://github.com/iovisor/bcc/blob/master/src/cc/frontends/clang/kbuild_helper.cc#L96

We already support ubuntu and arch (and I'm sure others as well). After we will complete this, we will support most major distros
