### ISSUE TITLE
No informative output when bpf build fails

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#343]
When running tracee without bpf code pre-compiled, compilation may fail for various reasons (usually kernel headers problem).
Currently, the error message is non informative: "exit status 1".

In this case, it is better if we showed the standard output in addition to the error message.

**Comment by itaysk** [comment]
it does print an error message: 
```
2020/12/03 16:56:35 missing kernel source code compilation dependency
```

**Comment by yanivagman** [comment]
I'm not referring to this failure of missing dependency, because this happens BEFORE you execute clang/llc/llvm-strip.
If any of these executions fails (which happens to be, for example, in #342 ) then only exit status is printed

**Comment by itaysk** [comment]
there's no way for us to tell why the build failed other than to look at the entire command output (is there?). if you want to see the entire output or to debug the build, you can run with the `--debug` flag. we don't show this by default in order to allow the output of tracee to be processed (e.g `tracee | awk ...`). what we can do is to print those errors to stderr.

**Comment by yanivagman** [comment]
The regular user is not aware of the "--debug" option, and you can't expect him to use it. 
Having "exit status 1" as the only output in case of a failure doesn't help in any way.
Instead, if we will show the command output in the case of a failure, the user will still be able to process tracee's output if everything worked fine, yet knowing what happened if there is a problem (like missing one specific header file)
