### ISSUE TITLE
Fix Gob Output Doc

### ISSUE THREAD

**Issue by jrmwooldridge** [aquasecurity/tracee#3471]
Please provide an example of using `gob` as an output? The documentation for using gob shows the output as still being `json`. I assume the use case for `gob` is golang IPC and RPC mechanisms, but that would be better as part of the documentation.

https://aquasecurity.github.io/tracee/v0.17/docs/outputs/output-formats/#gob

**Comment by yanivagman** [comment]
Hi @jrmwooldridge 
Originally we created the gob output to send tracee-ebpf events to tracee-rules. Since then, the architecture was changed, and tracee now uses a single binary that combines tracee-ebpf and rules. In addition, we are now in the process of creating a grpc based API (v1 will be released soon https://github.com/aquasecurity/tracee/issues/3208).
I'm not sure we will continue to support gob output, so we will probably remove its documentation as well

**Comment by jrmwooldridge** [comment]
Thanks for the heads up!
