### ISSUE TITLE
Improve docs structure

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#3607]
every section should have an overview page with talks about the purpose of the section and how to use it via config file.
then there can be other dedicated pages for cli flags, and for k8s experiences.

policies section
move filters page here as the cli experience
if/when we have kubernetes operator is will join here as k8x experience

integrations
container enrichment - we are making it default (separate task). move the setup related content to installation or advanced. then can remove the page.

events
restructures as:
- syscalls events
- network events
- security events
- lsm events
- containers events
- misc

create page for every security event like the rest
delete analyze page or reframe around testing custom signatures

**Comment by rafaeldtinoco** [comment]
1. Container Enrichment being the default now: https://github.com/aquasecurity/tracee/pull/3610 (and cmdline safeguard --no-containers for this release, to be removed in the next). I changed documentation to reflect that.

> Still need "Integrations" session name to be changed I believe.

2. Events restructured:

I'm still going to change https://aquasecurity.github.io/tracee/v0.18/docs/events/overview/ index page. I have mostly added signatures documentation (https://aquasecurity.github.io/tracee/dev/docs/events/builtin/signatures/)

After some thinking, I think the "security events" (Signatures) pages should be the first in the menu (because syscalls list is extensive, if user opens it they will just forget about the rest).

For now I kept:

![image](https://github.com/aquasecurity/tracee/assets/7395852/74da19c3-26f8-43cb-bcef-6a7345290fe3)

But I believe "extra" events should become "misc" ? and maybe add a "lsm events" explaining what they mean (avoiding TOCTOU etc).

**Comment by itaysk** [comment]
> But I believe "extra" events should become "misc" ? and maybe add a "lsm events" explaining what they mean (avoiding TOCTOU etc).

@rafaeldtinoco is this different from what the issue description suggests?

- syscalls events
- network events
- security events
- lsm events
- containers events
- misc

**Comment by rafaeldtinoco** [comment]
Just in order (having security events first). I'll also remove the word "events" at the end of each of them (keeping "Events" -> Security, Network, Misc, LSM, Syscalls, ...)

**Comment by AnaisUrlichs** [comment]
I think the Tracee docs overcomplicates things into separate terminology -- at the moment:

The `Events` Section details how to configure Tracee, including events it should track through the CLI https://aquasecurity.github.io/tracee/dev/docs/events/overview/#read-in-cli 

While the `Policy` section focuses on the Kubernetes experience https://aquasecurity.github.io/tracee/dev/docs/policies/ -- or is not specific about the environment -- However, in Kubernetes events are configured in the Policy

`Outputs` mainly focus on the CLI configuration but are separate from the `Config<Overview` part which showcases how to configure the CLI

We have a policy file which could be applied through Kubernetes installation or the CLI, and within that policy file users specify events or apply filters -- alternatively, they use the CLI to configure those -- or am I misunderstanding this?

I was brainstorming what an alternative structure could look like
![graphic(1)](https://github.com/aquasecurity/tracee/assets/33576047/50a906b4-1e81-4ed9-a5ca-3292fd3862ad)

**Comment by itaysk** [comment]
done!
