### ISSUE TITLE
Move 'Trace specific PIDs' from --trace to --filter

### ISSUE THREAD

**Issue by pathtofile** [aquasecurity/tracee#366]
To me, it doesn't make a lot of sense that filtering by pidnamespace or uid is done via `--filter`, but specific pids is done by `--trace`.

**Comment by pathtofile** [comment]
I do like `--filter` though, gj :-)

**Comment by yanivagman** [comment]
Hi @pathtofile we missed you here :-)

I see your point, and I tend to agree that we should move specific PIDs to filters.
We also had some thoughts about integrating --filter and --trace.
The reason why we kept this separation until now was that "--trace" represented a mode that should be mutual exclusive, while "--filter" could be given multiple times.
Me and @itaysk discussed possible ways to integrate "--filter" and "--trace" so things will be more intuitive.
A possible direction can be to only keep "--filter", but with the semantics we have today for mutual exclusiveness.
As filters use the "=" and trace mode use the ":" we can keep that and use it to our advantage.
Integrating this way will give us one "--filter" flag with the following options:

process:new
process:all
process:follow (new mode in PR)
container:new
container:all
host:new
host:all
pid=pid1,pid2,...
uid=uid1,uid2,...
pidns=pidns1,pidns2...
mntns=mntns1,mntns2...
uts=name1,name2,....
comm=comm1,comm2,...

This way, we can keep the logic we have now for mutual exclusive "mode", with one "filter" flag, where using ":" represents a mutual exclusive value, and "=" can be given multiple times.

WDYT?

**Comment by itaysk** [comment]
A more concise explanation to the same idea:

- Today `--filter` takes a `<key> <operator> <value>` pattern (e.g uid > 100, cmd = bash).
- Add a new operator to the filter expression -`:`, which does not describe comparison for the filter, but rather a behavior for the filter.
- Filters can be combined just like before with the exception that `:` operator can only appear once.

examples:
`--filter container:all --filter uid>1000`
`--filter process:follow --filter cmd=bash --filter uid=0`

**Comment by yanivagman** [comment]
A further simplification can be done by introducing a boolean "container" filter.
Then, the user can choose "container=true" which is container mode we have today, "container=false" which is host mode, and not specifying this filter is process mode.
Then we get the following options for "--filter":

container=false/true (doesn't have to be mutual exclusive)
pid=pid1,pid2,...
uid=uid1,uid2,...
pidns=pidns1,pidns2...
mntns=mntns1,mntns2...
uts=name1,name2,....
comm=comm1,comm2,...

Then we have the following mutual exclusive "modes":
process:new (default 'mode')
process:all
process:follow
container:new

Which we can represent as one mutual exclusive "mode" filter:
mode=new/follow/all

Where "new" is "process:new" when container=true is NOT set, and "container:new" if it is set.

WDYT?

**Comment by yanivagman** [comment]
I don't see your point that it is counter intuitive. On the contrary. It is much more intuitive.
When you don't specify a filter, you want to get all the values. In that case, the values are container=true and container=false, which means you want to get all the containers events + all the non container events.
From the user perspective, he doesn't care that you implement this filter with a mode or not. Who defines what is a "mode"? Us. And from the way I see it, a mode represents something that is mutual exclusive.
The values that should be mutual exclusive are new/all/follows, do you think otherwise?

**Comment by itaysk** [comment]
> I don't see your point that it is counter intuitive

usually when a setting is boolean, it has 2 states, on and off. in this case it has 3 states, on, off and undefined. this is unusual, and because it's unusual it's counter intuitive (not because of how you defined it)

> Who defines what is a "mode"? ... a mode represents something that is mutual exclusive.

I thought we were on the same page earlier but let me say how I thought of it: a mode is a kind of a filter, but where most filter operations are comparing values (e.g uid>1, cmd=ls), mode doesn't compare, it just defines a predefined filter. for example process follow can't be express with a comparison operator so we say it's a mode and the user should understand how it will filter.

**Comment by yanivagman** [comment]
Say that uid only had two values : 1 or 2.
Without any filter, you would expect it two catch both uids 1 and 2, right? Yet uid is boolean, and not tristate. How this is different from our case?

From the way I see it, a mode is something that is mutual exclusive. If I think about the user experience, container is just a "regular" filter

**Comment by pathtofile** [comment]
Hi @yanivagman! there's some awesome stuff going on with Tracee, I've been keeping tabs even though I haven't had more time to contribute :-) 

I don't have a strong enough opinion in any direction with this issue, so I'll let everyone else decide on the correct course of action

**Comment by itaysk** [comment]
I will give a few arguments here, please try to consider them individually:

For all filters, including UID that you used for example, omitting the filter intuitively means show everything - *simply because the name of the flag is "filter"*. This can't be said about any arbitrary flag, not the least about a "container" flag.

A mode is not just a mutual exclusive filter, it is different in nature from other filters because mode does not represent a comparison on one of the available event fields, unlike all other filters. For example, the single word "follow" represents dynamic filtering that is setup behind the scenes, but for the user it's just a single word. That's why I call it a "mode", not simply because it's mutually exclusive.

The mutual exclusivity rules that you allude to, are captured in greater fidelity in the unified approach. Separating "container" from "mode" implicitly means that all the modes apply to all states (container, process, host). You cannot express an unsupported combination besides as a validation error. In a unified model you can for example choose to support "process:follow", "container:follow", but not "host:follow".

I really don't think that anyone would find it intuitive that disabling the "container" boolean flag gives a different result than not including it, we could do a quick survey amongst our peers. But even still: I argue that a boolean value has maximum 2 states, you argue that its maximum 3 states, what if we had 4 states? Like Kubernetes pods for example.

**Comment by yanivagman** [comment]
> For all filters, including UID that you used for example, omitting the filter intuitively means show everything - simply because the name of the flag is "filter". This can't be said about any arbitrary flag, not the least about a "container" flag.

Now that I'm reading your response I'm not sure you understood what I'm suggesting.
I didn't say that we should add a new container flag that will stand by itself.
What I suggested is adding 'container' as a filter: "--filter container=true" for example.

> A mode is not just a mutual exclusive filter, it is different in nature from other filters because mode does not represent a comparison on one of the available event fields, unlike all other filters. For example, the single word "follow" represents dynamic filtering that is setup behind the scenes, but for the user it's just a single word. That's why I call it a "mode", not simply because it's mutually exclusive.

I didn't said modes are mutual exclusive filters, just that they are mutual exclusive.

> The mutual exclusivity rules that you allude to, are captured in greater fidelity in the unified approach. Separating "container" from "mode" implicitly means that all the modes apply to all states (container, process, host). You cannot express an unsupported combination besides as a validation error. In a unified model you can for example choose to support "process:follow", "container:follow", but not "host:follow".

I don't think that "state" is the right word to describe (container, process, host). Where do you think there is an unsupported combination in what I suggested? Trying to translate "host:follow" to the above filters will give "--filter container=false --filter follow" - this means that you want to trace all non container processes, and follow their childrens according to any further filters given - why do you find this problematic?

> I really don't think that anyone would find it intuitive that disabling the "container" boolean flag gives a different result than not including it, we could do a quick survey amongst our peers. But even still: I argue that a boolean value has maximum 2 states, you argue that its maximum 3 states, what if we had 4 states? Like Kubernetes pods for example.

Please refer to my answer for the first point

**Comment by itaysk** [comment]
we discussed this offline and settled to proceed with your proposal

**Comment by itaysk** [comment]
We can also move in filter-file-write in right?

**Comment by yanivagman** [comment]
I also thought about it, but I'm not sure it fits there.
This filter is only relevant to file writes (vfs_write(v)) events, and not to all events
