### ISSUE TITLE
Add ExportedDataSources to .so plugins

### ISSUE THREAD

**Issue by NDStrahilevitz** [aquasecurity/tracee#3705]
Currently our shared object plugins only support exporting signatures. Data Sources should be added as well. This can be done in the same way we use a convention for the `ExportedSignatures` symbol, we can add an `ExportedDataSources` symbol.

**Comment by yanivagman** [comment]
Actually I'm not sure we should invest in the shared object (.so) anymore since it simply doesn't work well (e.g. it is required to compile the .so with the same go version as tracee was compiled with). In addition to that, when tracee is compiled statically it can't load dynamic libraries (and we want to support statically compiled binary so tracee can run without any other dependency).
The only use case I can think of for having .so is to update signatures in runtime, however, this use case can also be achieved by updating the tracee binary itself. In the future, we should consider a different mechanism to update signatures, but I don't think .so will be the best solution.

**Comment by NDStrahilevitz** [comment]
Since extensions, or any other replacement for the .so for that matter, are not on this milestone, and we have a need for externally pluggable data sources due to #3704 in this milestone, I think this is still needed, especially since it's not a very large change (data sources and signatures should be very similar in terms of exporting and registering).
When we replace the .so we can move both of these together.

**Comment by rafaeldtinoco** [comment]
> Since extensions, or any other replacement for the .so for that matter, are not on this milestone, and we have a need for externally pluggable data sources due to #3704 in this milestone, I think this is still needed,

You have a good point.
