### ISSUE TITLE
grpc: add map support to event data

### ISSUE THREAD

**Issue by josedonizetti** [aquasecurity/tracee#3843]
I was considering adding support for `map[string]string` to event data, as we had some args as `map[string]string` in the old event structure, but turns out that places we are using `map[string]string` are actually to [`Sockaddr`](https://github.com/aquasecurity/tracee/blob/main/pkg/bufferdecoder/eventsreader.go#L251), and we already have a protobuf [message](https://github.com/aquasecurity/tracee/blob/main/api/v1beta1/event_data.proto#L86).

Though a `map` struct might sill be useful, we have something like it with https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto, but the values are limited to:

```
NullValue null_value = 1;
double number_value = 2;
string string_value = 3;  
bool bool_value = 4;  
Struct struct_value = 5;  
ListValue list_value = 6;
```
  

wonder if we should drop `Struct` and instead have a `map[String]EventValue`, as `EventValue` support more options.

**Comment by josedonizetti** [comment]
@yanivagman @NDStrahilevitz thoughts?

**Comment by yanivagman** [comment]
That's an option, though I don't understand what will be the use case for that

**Comment by NDStrahilevitz** [comment]
If we could have this as a recursive structure I think it would be great (and we may want to migrate to this option in writable data sources too). Otherwise I think `Struct` has the recursive property included which adds a benefit.

@yanivagman I think this is relevant for custom events, where an author may need to define a custom marshal to protobuf of a new argument type.

**Comment by josedonizetti** [comment]
After chatting with @yanivagman, this won't be needed.
