### ISSUE TITLE
Collecting all event for specific process or pid

### ISSUE THREAD

**Issue by sankyhack** [aquasecurity/tracee#4465]

**Comment by yanivagman** [comment]
There are scope filters that will let you select a specific process or pid, see here: https://aquasecurity.github.io/tracee/dev/docs/policies/scopes/

Slecting all events is possible from CLI using `-e '*'` but I don't recommend that, since the frequency of some events is very high, and probably won't give you much. You can select specific events from the available list, see here https://aquasecurity.github.io/tracee/dev/docs/events/
