### ISSUE TITLE
Add ringbuffers support to libbpfgo for output

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#448]
ring buffers are nice to use over perf buffers because events will come in order from the kernel to userspace. However, it's important to be conscious of performance changes (i'm not sure what the impact would be if any, good or bad).

[This was added in kernel 5.8](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=457f44363a8894135c85b7a9afd2bd8196db24ab), so while it will be useful to have in libbpfgo, we have to think about strategy for feature flagging it in tracee itself. 

[relevant docs](https://www.kernel.org/doc/html/latest/bpf/ringbuf.html)

**Comment by yanivagman** [comment]
I mentioned this in #219 .
Indeed, ringbuffer support are the preferred way to submit events starting from kernel 5.8 not only because event order is kept, but also because it has better performance and other advantages.
More info: https://nakryiko.com/posts/bpf-ringbuf/

**Comment by simar7** [comment]
+1 on feature flagging. I think the eBPF space will continue to keep evolving which would result in scenarios like this where a certain feature might only be available on a newer kernel version. Rather than bumping the minimum supported kernel version, we can feature flag certain features where they can still be present in the shipped tracee releases but only work on supported kernels.
