### ISSUE TITLE
repackage tracee container image

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#463]
currently aquasec/tracee image is just tracee-ebpf. the next release will need to release tracee-ebpf as well as tracee-rules under the aquasec/tracee container. we should repackage the container (dockerfile) with these artifacts. the dockerfile should move out of tracee-ebpf to the root

**Comment by yanivagman** [comment]
I think that it can be usefull to have a separate image for tracee-ebpf.
It shouldn't cost a thing from us, should it?

**Comment by itaysk** [comment]
Yeah after a discussion with liz we decided to focus on just one image called tracee which will be the entrypoint to everything. In order to not cause too much confusion, and to signal that everything is still "tracee" it's just composed of different components now. If you think otherwise we can release another image though

**Comment by yanivagman** [comment]
Yes, I think that we should realease another image, as it is self contained, and useful by itself.
We can concentrate in one "tracee" container like you said, while still having a different image for tracee-ebpf as it doesn't require anything from us.
Users who only need tracing (and forensics) capabilities, can just use it instead of the "tracee" image and have a simpler UX for their needs.

**Comment by itaysk** [comment]
my concern is never what it requires from us but what it requires from the user. the concern was that adding a new image will have more cons then pros, and will create friction. I'm not strongly opinionated about this though
