### ISSUE TITLE
Document or automate the checking out of the libbpf git submodule

### ISSUE THREAD

**Issue by grantseltzer** [aquasecurity/tracee#484]
In order to build `tracee-ebpf` we need the libbpf source code which is maintained as a git submodule. We should document this [here](https://github.com/aquasecurity/tracee/tree/main/tracee-ebpf#setup-options) or automate the process of initializing/updating it in the `Makefile`.

I like the latter option better but is there any downside to this?

**Comment by itaysk** [comment]
we used to include it in the makefile and I recently removed it because in monorepo it broke the build.
I'm fine with either way, just to explain the tradeoff:
Now it's logically 2 separate phases: 1. fetch the source code 2. build the executable. 
Before, the build phase actually fetched more source code, which might be better done in the fetch phase.
If you look at the GH actions workflow it makes more sense.

so yes I agree right we need to either document or auto fetch. I'm fine with either.

**Comment by simar7** [comment]
I would vote for auto-fetch, this gets me every time I start afresh 😄

**Comment by rafaeldtinoco** [comment]
We have this automated at:

https://github.com/aquasecurity/tracee/blob/main/Makefile.one#L303

Is that enough to close this ?

**Comment by yanivagman** [comment]
> We have this automated at:
> 
> https://github.com/aquasecurity/tracee/blob/main/Makefile.one#L303
> 
> Is that enough to close this ?

I think so, yes
