### ISSUE TITLE
benchmark rego and go signatures

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#506]
understand the performance characteristics of go signatures and rego signatures. We should pick a set of comparable signatures (in terms of complexity) and test them under stress.

**Comment by yanivagman** [comment]
Since the creation of this issue, there were some tests done by @simar7 @danielpacak and @grantseltzer to benchmark the performance of rego and go signatures(#785 #790 #792) .
We can update about the progress here and maybe close it in favor of other new issues opened as part of the conclusions of these tests.
