### ISSUE TITLE
--rules-dir flag doesn't work in some cases

### ISSUE THREAD

**Issue by simar7** [aquasecurity/tracee#579]
**What I observed**
This is on the `main` branch of Tracee
```
dist/tracee-rules --rules-dir="signatures"                                              
2021/02/23 15:11:16 error reading file signatures/helpers.rego: open signatures/helpers.rego: no such file or directory
2021/02/23 15:11:16 open signatures/helpers.rego: no such file or directory
```

**What I expected**
Passing in the `signatures` dir should recursively grab all (both rego and Golang) signatures contained within that directory.
```
dist/tracee-rules --rules-dir="signatures"
```
Assuming `signatures` directory exists as it does today with the Tracee repo, this should be a valid `tracee-rules` invocation. Also assuming `helpers.rego` is contained within the directory.

As a user I can technically have both type signatures living (rego and go) in the same directory and `tracee-rules` should be smart enough to figure that out I feel.

**Comment by itaysk** [comment]
> As a user I can technically have both type signatures living (rego and go) in the same directory  

you can (actually you must). the error is unrelated to go/rego coexistence. it's related to tracee-rules expecting to find the rego helpers in the same directory.

You got an error because you have run tracee-rules while giving it the signatures source, not the output in dist. the "fix" to this is to remove the `--rules-dir` flag. a normal user which runs tracee as instructed would not encounter this.

There are a couple of potential improvements we can make:
1. recursively load signatures - PR in flight: https://github.com/aquasecurity/tracee/pull/503 (not that even this PR won't solve the particular issue you were having)
2. make helpers.rego a built-in feature of tracee by embedding it into the executable. I've been thinking about this while creating the helpers but didn't want to create a dependency on https://github.com/aquasecurity/tracee/issues/434

**Comment by simar7** [comment]
Having discussed this offline, we can close this. This was an operator error.
