### ISSUE TITLE
Unable to run tracee-ebpf, failed to create kprobe event (0.5.0)

### ISSUE THREAD

**Issue by bionic-simcha** [aquasecurity/tracee#639]
After downloading from releases I notice there is a stark difference between what is in the YouTube videos and README, and what was downloaded in the v0.5.0 zip. When attempting to copy what was done in the v0.4.0 YouTube video I ended up with this error:

```
$sudo ./tracee/dist/tracee-ebpf --trace pid=new
failed to add kprobe 'p:kprobes/psecurity_bprm_check security_bprm_check': -17
failed to create kprobe event: -17
```
I noticed there is another issue like this (issue #447) however I am simply trying to run the program and not worried about clean up just yet.

This echos the sentiment in issue #637

**Comment by grantseltzer** [comment]
Hi @bionic-simcha, I'm sorry about your frustration. Just to confirm what the issue is, can you try running the following command and see if it fixes the issue:

`sudo bash -c "echo "" > /sys/kernel/debug/tracing/kprobe_events"`

As you mentioned, issue #447 seems related. This was fixed in #551, but that was after 0.5.0 release. It seems we should release 0.5.1 to include this fix. 

Thanks for your patience and for reporting the issue!

**Comment by bionic-simcha** [comment]
That fixed it, thank you! You don't have to explain here but do you have resources for me to dig into this further for curiosities sake; I'm not too familiar with kprobe_events.

**Comment by yanivagman** [comment]
Hi @bionic-simcha 
Eching an empty string to kprobe_events file clears the existing kprobes. The bug we had was caused by an improper close of tracee, which kept the kprobes set after the process exited. Due to this, the next time tracee started, it couldn't set the same kprobes again (which have the same names between different runs of tracee), and returned errno 17 (file exists).
We recently bumped the minimal kernel version to 4.18, which helped in resolving this issue. Now we use a different attach mechanism for kprobes, which doesn't require to create a file in tracefs for setting a kprobe - thus this problem is now resolved.
