### ISSUE TITLE
connect's sock_addr is incorrectly printed as void*

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee#666]
Example from @eidans :

```
{"timestamp":230676.007252,"processId":157182,"threadId":157197,"parentProcessId":157175,"hostProcessId":157182,"hostThreadId":157197,"hostParentProcessId":157175,"userId":1000,"mountNamespace":4026531840,"pidNamespace":4026531836,"processName":"Chrome_ChildIOT","hostName":"MichaelsLenovo","eventId":"42","eventName":"connect","argsNum":3,"returnValue":-101,"stackAddresses":null,"args":[{"name":"sockfd","type":"int","value":36},{"name":"addr","type":"void*","value":"{'sin6_flowinfo': '0','sin6_addr': '2001:4860:4860::8888','sin6_scopeid': '0','sa_family': 'AF_INET6','sin6_port': '53'}"},{"name":"addrlen","type":"int*","value":28}]}
```

Note the: `{"name":"addr","type":"void*","value"...}`
Should be: `{"name":"addr","type":"struct sockaddr*","value"...}`

When fed into tracee-rules it (correctly) gives an unmarshaling error:

```
2021/04/01 15:06:27 invalid json in {"timestamp":230676.007252,"processId":157182,"threadId":157197,"parentProcessId":157175,"hostProcessId":157182,"hostThreadId":157197,"hostParentProcessId":157175,"userId":1000,"mountNamespace":4026531840,"pidNamespace":4026531836,"processName":"Chrome_ChildIOT","hostName":"MichaelsLenovo","eventId":"42","eventName":"connect","argsNum":3,"returnValue":-101,"stackAddresses":null,"args":[{"name":"sockfd","type":"int","value":36},{"name":"addr","type":"void*","value":"{'sin6_flowinfo': '0','sin6_addr': '2001:4860:4860::8888','sin6_scopeid': '0','sa_family': 'AF_INET6','sin6_port': '53'}"},{"name":"addrlen","type":"int*","value":28}]}: unrecognized argument type
2021/04/01 15:06:27 invalid json in {"timestamp":230676.007961,"processId":157182,"threadId":3919697,"parentProcessId":157175,"hostProcessId":157182,"hostThreadId":3919697,"hostParentProcessId":157175,"userId":1000,"mountNamespace":4026531840,"pidNamespace":4026531836,"processName":"ThreadPoolForeg","hostName":"MichaelsLenovo","eventId":"49","eventName":"bind","argsNum":3,"returnValue":0,"stackAddresses
```

I'm able to reproduce with main:

```
❯ ./tracee-ebpf  -o gotemplate=<(echo '{{index .Args 1 }}') -t event=connect
{{addr void*} {'sa_family': 'AF_UNIX','sun_path': '/var/run/nscd/socket'}}
```

**Comment by itaysk** [comment]
something's weird. I start a trace, and:
1. open a new terminal (which in my setup makes some outbound connection), those will be `void*`!
2. if I make some outbound connection form an opened terminal, those will be `sockaddr*`!
3. if I open a new terminal and in it make an outbound connection, it will be `sockaddr*` (both of them)!
4. same as 3 in reverse order - `sockaddr*`

**Comment by itaysk** [comment]
possibly related to #665 . I've seen inconsistent behavior there as well

**Comment by itaysk** [comment]
even weirder, tried again and it is shown as `unsigned long`

**Comment by grantseltzer** [comment]
@yanivagman I believe this is related to the code here, but I don't quite understand what you did here:

https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.go#L488-L493

What is the purpose of storing the parameter and type names in this way?

**Comment by yanivagman** [comment]
@grantseltzer I don't think it is related to this problem. The code you linked to is encoding the event's parameter names, and not the types. The types are being encoded in the switch-case above the quoted lines.

I"ll try to have a look at this bug on sunday if no solution will be found by then

**Comment by yanivagman** [comment]
Ok, so I took a quick look at it now and I think that I know what is the root cause of this bug.
After all, you are right @grantseltzer and the lines you quoted are the offending lines.

When I wrote the original code, it was only parameter names that were saved to the DecParamName map, but since then, PR #388 changed this to be a mix of parameter name and type. Specifically, the line which introduced the change is:
https://github.com/aquasecurity/tracee/commit/f1968a7d2b7a1fc78f3ce7a6ecd27cff0f73e99b#diff-82aa2eb77c3ce782b8ebfb70eaba8a1a5a8a2dce9f3349352a3a3c0f909478f1R375
so now all the metadata (arg name + type) is saved in this map.
This is problematic because that map was not meant to save parameter types, but only names.
The idea of how names are being saved to this map is the following:
1. Given an argument name, encode it to some opaque number using the map EncParamName. Also save the reverse mapping in DecParamName map (https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.go#L491)
2. This number is then encoded with all the other arguments of the event in https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.go#L740 so the bpf code can read it from the map, and send it back to userspace for decoding when the event happens.
3. Userspace then decodes this number back in https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/pipeline.go#L161 to a name which can then be printed.

Using this method has the advantage that it is self contained. Even if the bpf code failed to read some argument (and sent less arguments than what was expected), we can still decode it correctly as the event has all the required data about the arguments names, types, and values.

Mixing the type into the EncParamName and DecParamName maps is problematic as different syscalls (or events in general) may have the same parameter names. For example, addr is an argument of the mmap syscall with type void*, while it is also an argument of the connect syscall but with type "struct sockaddr". But if we already seen an argument with this name, we don't save it again to the ENC and DEC maps: https://github.com/aquasecurity/tracee/blob/main/tracee-ebpf/tracee/tracee.go#L495. As our events are saved in a map (EventsIDToEvent map), the order in which the events are being read during init is not deterministic, which may cause the exact same issues described here.

To solve this problem, I think that first these maps should be used as they were intended to be used - to only save the arguments names. Then, to get the argument type while it is being decoded in the pipeline, we can use the event id and argument name to extract the type from the EventsIDToParams map.
