### ISSUE TITLE
Tracee not collecting threads syscalls 

### ISSUE THREAD

**Issue by galsinger29** [aquasecurity/tracee#772]
From version 0.4.0 onward, tracee is not collection syscalls of threads under a process, only the parent process syscalls.

the command line of tracee used:
'docker run --name tracee --rm --privileged -v /lib/modules/:/lib/modules/:ro -v /usr/src:/usr/src:ro -v /tmp/tracee:/tmp/tracee -it aquasec/tracee:0.4.0 -b 1024 --blob-perf-buffer-size 16384 -t c'

**Comment by yanivagman** [comment]
Thanks for reporting this issue.
The problem is that tracee use the return value from fork to add new threads to its traced pid list.
When a container filter is given, as in your case, the pid returned by the fork syscall is inside the container namespace, and not the pid on the host.
Interesting that I already opened a PR that fixes this issue before I even knew about it :-) 
This will be resolved by #767
