### ISSUE TITLE
helpers.rego and helpers.go should be loaded dynamically 

### ISSUE THREAD

**Issue by idanr1986** [aquasecurity/tracee#780]

**Comment by eidans** [comment]
@itaysk , do we have an ETA for this?

**Comment by itaysk** [comment]
It's not in the backlog yet. needs to be discussed further as I don't think the use-case is obvious from the title, and then prioritized. can you elaborate on the use-case?

**Comment by eidans** [comment]
We want to load go signatures that are not compiled with tracee-rules
binary. As I understand, it is not possible today as the helpers file is
statically compiles with tracee-rules.

**Comment by itaysk** [comment]
> We want to load go signatures that are not compiled with tracee-rules
binary. As I understand, it is not possible today as the helpers file is
statically compiles with tracee-rules.

It's true that helpers.go is compiled with tracee-rules. that's good because it makes it available to everyone to use. But that doesn't have anything to do with your ability to dynamically load go signatures - that's possible today, just build the policies and put the file in the rules directory and tracee-rules will discover and load it.
Let me know if I missed something

**Comment by itaysk** [comment]
To address the original request, I think we modify the helpers loading logic. Today we specifically look for helpers.rego and load it to all the rego instances. We can instead look for `*_helpers.rego` which will allow anyone to write their own helpers file which will be available to all the signatures.
