### ISSUE TITLE
Error building Tracee on Ubuntu 20.04.2 LTS kernel 5.4.0-73-generic

### ISSUE THREAD

**Issue by idanr1986** [aquasecurity/tracee#828]
while executing `make docker` I get `make: mkdir: Operation not permitted`

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
docker build --build-arg VERSION=0 --build-arg BUILD_DATE=2021-07-19T19:12:26Z --build-arg VCS_BRANCH="" --build-arg VCS_REF="" -t tracee:latest .
Sending build context to Docker daemon  1.042MB
Step 1/23 : ARG BASE=fat
Step 2/23 : FROM golang:1.16-alpine as builder
 ---> 7762f5dece68
Step 3/23 : RUN apk --no-cache update && apk --no-cache add git clang llvm make gcc libc6-compat coreutils linux-headers musl-dev elfutils-dev libelf-static zlib-static
 ---> Using cache
 ---> 43f7119b67f1
Step 4/23 : WORKDIR /tracee
 ---> Using cache
 ---> 3a08e75d98b8
Step 5/23 : FROM builder as build
 ---> 3a08e75d98b8
Step 6/23 : ARG VERSION
 ---> Using cache
 ---> 2cf6c5026aee
Step 7/23 : COPY . /tracee
 ---> Using cache
 ---> aef8a7671824
Step 8/23 : RUN make
 ---> Running in feaec81d439f
`make: mkdir: Operation not permitted`
`make: *** [Makefile:32: dist] Error 127`
`mkdir -p dist`
The command '/bin/sh -c make' returned a non-zero code: 2
make: *** [Makefile:59: docker] Error 2

**Comment by idanr1986** [comment]
I found a fix to this issue by editing the `Dockerfile` and changing the builder image from `golang:1.16-alpine` to ` golang:1.16-alpine3.13` from what I concluded the issue happens from alpine 3.14.
here are some references to the issue:
https://forums.docker.com/t/multiple-projects-stopped-building-on-docker-hub-operation-not-permitted/92570/4
https://gitlab.alpinelinux.org/alpine/aports/-/issues/12396

**Comment by rafaeldtinoco** [comment]
Yes, the problem might be related to coreutils and kernel support:

```
This is happening because the Docker Hub hosts run old kernels that are not compatible with the latest GNU coreutils, specifically the statx system calls.

The Docker host kernels don’t properly announce their version and hence alert coreutils that they can’t make statx calls, something they would normally gracefully work around.

This is not just Arch Linux, all distributions with new packages are hitting the same issue. Recent builds of Fedora have the same problem, SUSE Tumbleweed, etc.
```

Not entirely sure this comment is accurate, but might be related. As you mention, you are running: 20.04.2 LTS kernel 5.4.0-73-generic (which is the latest), but yet user-land might be facing issues with core-utils.

```
 coreutils | 8.28-1ubuntu1       | bionic           | source
 coreutils | 8.30-3ubuntu2       | focal            | source
 coreutils | 8.32-3ubuntu1       | groovy           | source
 coreutils | 8.32-4ubuntu2       | hirsute          | source
 coreutils | 8.32-4ubuntu2       | impish           | source
````
Ubuntu Focal does not have a fix for core-utils... I'll check.

**Comment by rafaeldtinoco** [comment]
Okay, 

The BUG is related to new **MUSL** library in **ALPINE** (libc replacement). It has started using **faccesstat2** system call and this syscall is having problems whenever **runc** has seccomp enabled. The **runc** (with seccomp enabled) code is not returning the proper error (ENOSYS) to issuer of this syscall (to say it is not supported).

* The alpine BUG is described [HERE](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2) .
* The runc BUG is described [HERE](https://github.com/opencontainers/runc/issues/2151).

### Request 1)

It is likely that a reproducer is this:

```
$ docker run -it alpine:edge /bin/sh

/ # apk update

/ # apk add git build-base
```

Save the following code as faccesstat2.c :

```C
#include <stdio.h>
#include <errno.h>
#include <unistd.h>
#include <stdlib.h>
#include <dirent.h>
#include <fcntl.h>
#include <sys/syscall.h>
#include <sys/types.h>

#define __NR_faccessat2 439

int main(void)
{
	int ret;
	DIR *d = opendir(".");

	ret = syscall(__NR_faccessat2, d, "/mnt",  R_OK | W_OK | X_OK, 0);
	if (ret < 0) {
		perror("syscall");
		fprintf(stderr, "errno: %d\n", errno);
		exit(1);
	}

	closedir(d);
	exit(0);
}
```

Compile and run it :

```
~ # gcc faccesstat2.c -o faccesstat2

~ # ./faccesstat2
syscall: Function not implemented
errno: 38
```

I'm interested in your output.

### Request 2)

Could you please share the **seccomp profile** you are currently using AND **check if this error happens when you run the container unconfined** ? (You can also provide output of the same reproducer in an unconfined container, it would be good to have output from it).

### Request 3)

Could you also please check **runc** package you are currently using  by doing:

```
$ dpkg-query -f '${Package} ${Version}\n' -W 'runc'
runc 1.0.0~rc95-0ubuntu1~20.04.1
```

Because there is an update to the package:

```
$ rmadison -u ubuntu -a amd64 runc -s focal,focal-updates
 runc                                  | 1.0.0~rc10-0ubuntu1         | focal         | amd64
 runc                                  | 1.0.0~rc95-0ubuntu1~20.04.1 | focal-updates | amd64
```

That is actually a 'micro release' update.

**Comment by rafaeldtinoco** [comment]
There is a workaround to make opencontainers to override default errno:

https://github.com/opencontainers/runtime-spec/pull/1087/commits

This way they can 'fix' this issue in the container side (wrap the error and change it).

**Comment by rafaeldtinoco** [comment]
I think I reproduced the issue...

With the following profile:

```json
$ cat profile.json 
{
    "defaultAction": "SCMP_ACT_ALLOW",
    "syscalls": [
        {
            "names": [
                "faccessat2"
            ],
            "action": "SCMP_ACT_ERRNO",
   "args": [],
   "comment": "",
   "includes": {},
   "excludes": {}
        }
    ]
}

```

I'm disallowing the faccessat2 system call by using a seccomp profile. 

Instead of receiving a:

```
~ # ./faccessat2
syscall: Function not implemented
errno: 38
```

we receive a:

```
/ # ./faccessat2
syscall: Operation not permitted
errno two: 1
```

And that makes musl confused. So best way to proceed here, on our side, is to always allow faccessat2 system call in the ubuntu profile (at least for now) OR something like it.

**Comment by itaysk** [comment]
@rafaeldtinoco thank for the analysis. I'm not sure I understood the solution (workaround you mentioned), is there a fix required on our side?

**Comment by rafaeldtinoco** [comment]
> @rafaeldtinoco thank for the analysis. I'm not sure I understood the solution (workaround you mentioned), is there a fix required on our side?

I'm not sure why @idanr1986 's environment is failing. I'm currently using a similar kernel and docker.io packages from Ubuntu Focal (but updated to the latest) and cannot reproduce. My bet is that _his environment_ is enforcing some kind of changed profile by default, which is causing the change of errors (forbidding faccessat2 syscall) from the syscall.

With that said, we can create a file called 'build-profile.json' in our builder:

```json
{
    "defaultAction": "SCMP_ACT_ALLOW",
    "syscalls": [
        {
            "names": [
                "faccessat",
                "faccessat2"
            ],
            "action": "SCMP_ACT_ERRNO",
   "args": [],
   "comment": "",
   "includes": {},
   "excludes": {}
        }
    ]
}
```

and execute docker with:

docker run -it --security-opt seccomp=./profile.json alpine:edge /bin/sh
(or in our case change Dockerfile to use this build-profile.json)

and we would mitigate this issue for @idanr1986 and others facing the same problem.

**Comment by rafaeldtinoco** [comment]
The branch above deals with the issue (after all this theory) and I'd like it to be tested, if possible.

**Comment by rafaeldtinoco** [comment]
@itaysk Should we do something here ? To have the build workaround (this or a polished version of this) in tracee's Makefile ? 

> I don't see upstream fixing this issue right now, as the issue is closed, and even if they do.. the distributions would have to pick the bug and that could lead to long time with broken builds in older kernels.

**Comment by yanivagman** [comment]
For now, maybe we can change the dockerfile to point to a previous tag of alpine instead of latest to workaround this?

**Comment by rafaeldtinoco** [comment]
Changing dockerfile to pointing to previous alpine will mitigate the issue.

On the other hand, to continue this I need:

- A reproducer: Is docker packages installed from ubuntu repositories ? I cannot reproduce the issue with those.
- My install: Installs 20.04.2 LTS and apply all the updates (from -updates repository) before doing the build.
- Only way to reproduce the issue was to forbid the syscall in a seccomp profile (which is not the default).

By having those answers I'll know where to go to fix this so we can always have latest alpine.

**Comment by rafaeldtinoco** [comment]
Nevermind, I have just reproduced the issue:

```
Step 8/23 : RUN make
 ---> Running in 094510e348aa
make: /bin/sh: Operation not permitted
make: *** [Makefile:40: dist/tracee-ebpf] Error 127
```

In a recent installed without ANY updates environment. I'll isolate kernel and OS upgrades to see what mitigates the issue. Then we will have to decide whether we want the workaround in the Makefile (to cover building in outdated environments) or just document here that one using Ubuntu should apply all updates to it before building tracee.

**Comment by rafaeldtinoco** [comment]
@idanr1986 and @yanivagman 

**The FIX is to update your environment (Ubuntu Focal)** 

```
deb http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
```

BUT, if you cannot do that, then AT LEAST upgrade 

**runc package from `1.0.0~rc10-0ubuntu1` TO `1.0.0~rc95-0ubuntu1~20.04.1`**

It contains the mitigation for this issue. I'll bisect runc changes and see what is the specific fix.

**Comment by rafaeldtinoco** [comment]
And the **runc** commit in between these 2 versions that fixed the issue is this one:

**seccomp: prepend -ENOSYS stub to all filters**
https://github.com/opencontainers/runc/commit/7a8d7162f9d72f20d83eaa36aeb5426deecd58f2

> Which is exactly related to the initial analysis, but with a fix made in runc. I think just having this issue as closed with these comments will document enough information for one (to update runc for building tracee) and that no changes in our side are needed.

**Comment by yanivagman** [comment]
@rafaeldtinoco thanks for the analysis.
From the above I understand that there is no issue here for tracee, and we can close this, right?

**Comment by rafaeldtinoco** [comment]
Correct IMO, it is well documented for whoever needs it. Closing this then. Thank you.
