### ISSUE TITLE
Capability to filter out events by process ancestry

### ISSUE THREAD

**Issue by mtcherni95** [aquasecurity/tracee#836]

**Comment by yanivagman** [comment]
Please explain. What is missing? You can already use pid!=123 or comm!=xyz

**Comment by mtcherni95** [comment]
the use case is the following:
process A forks B, C, and D. I would like to not get any event from A, B, C and D knowing only that A exists.

**Comment by yanivagman** [comment]
If the names of the processes is known in advance, you can filter out by it.
Also, are these processes part of the same container? If so, you can use, for example, mnt_ns!=12345 to not trace that comntainer.

**Comment by mtcherni95** [comment]
> If the names of the processes is known in advance, you can filter out by it.
> Also, are these processes part of the same container? If so, you can use, for example, mnt_ns!=12345 to not trace that comntainer.

that's the thing, the name of the children processes are not known in advance.
using mnt_ns might help however the processes:
1. are running on host namespace
2. go in/out their ns

**Comment by yanivagman** [comment]
Ok. I understand the use case.
There are several questions that need to be answered before implementing such a feature:
1. Do we want to implement this in the bpf code or userspace? Implementing another filter in the kernel means more instructions for every event, and if we do so, we need to make sure we don't pass the instructions limit in old kernel (4.18-5.2). On the other hand, implementing this in userspace is less efficient as we have to send the event to the userspace first, which requires more processing.
2. If we choose to implement this in the kernel, this can be done by adding the forked pids to the pid_filter. If we do that, should we also do that to other filters as well? The logic says yes, but then again, this means even more code added to the filters logic in the kernel.
3. How will this be exposed to the user from the command line? We currently have the "follow" filter to follow forks of processes that passed all filters. The required feature is somehow the same, but with the opposite functionality - If something was filtered out explicitly, then don't follow its descendants. Maybe we can make this flag more generic to reflect that?

**Comment by grantseltzer** [comment]
> the use case is the following:
> process A forks B, C, and D. I would like to not get any event from A, B, C and D knowing only that A exists.

In this situation, what do you know about A? PID? Command name? or any existing filter?

Would having a filter by PPID satisfy this? Or any process in the process tree under a particular PID?

**Comment by itaysk** [comment]
@mtcherni95 @yanivagman how do you suggest to address this request? from an end-user perspective I think it would make most sense if we could make follow an operator-level modifier, but I'm not sure if feasible.

**Comment by mtcherni95** [comment]
regarding process A you know the process name (aka A :) ). we also know the binary name if that could help.

**Comment by yanivagman** [comment]
> @mtcherni95 @yanivagman how do you suggest to address this request? from an end-user perspective I think it would make most sense if we could make follow an operator-level modifier, but I'm not sure if feasible.

Can you please give an example for "an operator-level modifier"? I don't think that using "!follow" will be clear to the user.

**Comment by eidans** [comment]
Another possible representation that came up during our discussion is to provide a ‘tree’ filter as follows: tree=pid, will track only the process tree hierarchy that pid is the root. And tree!=pid, will exclude the process tree that has pid as root. User can combine both filters. @itaysk WDYT?

**Comment by grantseltzer** [comment]
This requires us to build an entire process tree model in bpf. On startup trace the process tree, and update on every fork and exit.

**Comment by itaysk** [comment]
> Can you please give an example for "an operator-level modifier"? I don't think that using "!follow" will be clear to the user, and is also ambiguous.

I meant that follow would apply to a specific filter, not the entire trace expression as today. consider the trace expression pid>123 and pid!=321. if we add follow it means all the processes that are greater then 123 except 321, and all of their decedents. but if I could to specifically add follow to pid>123, it means all the processes that are greater then 123 and their descendants, except 321 (but just it). now that I'm writing it I'm not so sure it's best but that was what I meant.

**Comment by itaysk** [comment]
I think tree=123 is a better suggestion

**Comment by yanivagman** [comment]
I prefer to add a tree filter (as I told @eidans), and not to change the semantics of follow. What we want to implement here is the ability to trace or not to trace a process tree given by the user. Follow has a different semantic - it applies not only to the pid filter, but to any other filter of tracee that should match to follow.

Now say that we choose to implement this using `--trace tree!=X` where X is the root of some process tree.
In that case, we will first need to understand (on tracee init) which pids are part of this process tree. This can be done by traversing procfs starting from process X. When doing that, we also need to take into account that our init process populates the bpf maps before the bpf programs have started, which means that there is a potential race condition here of a process that started after traversing the tree, or a process which exited after that point (This can be solved by doing another traversal after the bpf programs are loaded and attached).

I think that the implementation should be in the kernel, and not in userspace, so it will be more efficient. I will describe a possible implementation below, but any implementation done in the kernel will need to be verified in kernel<5.2, where there is an instruction limit of 4096 instructions.

Possible implementation:
1. Define a new map in the kernel - `process_tree_map` with a key that will represent a pid, and a value that will reresent if the process (and its descendants) should be traced or not.
2. Populate this map during the init phase of tracee, as described above
3. Update sched_process_fork event as follows: If the parent pid is in process_tree_map, add the child pid as well with the same value as of its parent.
4. Update should_trace as follows: if tree filter was not given (should be part of the config map) - continue as usual. Otherwise, check if pid exists in process_tree_map and get its value. Decide if to continue the checks or not based on this value.
